### ISSUE TITLE
upgrade --all installs packages that are already up to date

### ISSUE THREAD

**Issue by jpbnetley** [microsoft/winget-cli#1075]
# Brief description of your issue
When I run the `winget upgrade --all` winget tries to upgrade software that are already the latest.
In this example, it tried to update 2 software.
- AIMP
- Discord.

I should mention that I had these apps installed form their respected websites before I had winget installed.
# Steps to reproduce

I opened the term application as admin, and executed `winget upgrade --all`
In the attached screenshot, you will see I have discord, and AIMP open with their versions before I ran the update.
![winget upgrade](https://user-images.githubusercontent.com/25173863/120485642-979b5080-c3b4-11eb-9d79-c8c573b52ba8.jpg)

Discord's installed version is `1.0.9002`
AIMP's installed version is `4.70.2251`

Initially I thought it might be related to this issue: https://github.com/microsoft/winget-cli/issues/696#issuecomment-771856473
But when I checked the versions for both apps, I saw that winget lists the same versions that was installed.
To see the discord version, I ran: `winget search discord`
To see the AIMP version, I ran: `winget search aimp`

# Expected behavior

I expected that when the upgrade command is executed, that software that are up to date doesn't try to download and install the same version.

# Actual behavior

Up to date software gets re-downloaded and installed (in the example, Discord and AIMP).

# Environment

```none
[winget --info]
Windows Package Manager version: v1.0.11451
Windows: Windows.Desktop version: v10.0.19043.985
Package: Microsoft.DesktopAppInstaller version:  v1.11.11451.0

Any other software?
```

**Comment by jpbnetley** [comment]
I did see this issue looks to be related: https://github.com/microsoft/winget-cli/issues/1009

And saw he ran `winget upgrade`
I did the same, and saw that the versions don't match, this the reason it tries to install already up to date versions.

```
Name                          Id                                     Version                Available            Source
-----------------------------------------------------------------------------------------------------------------------
AIMP                          AIMP.AIMP                              v4.70.2251, 23.05.2021 4.70.2251            winget
Battle.Net                  Blizzard.BattleNet                     Unknown                      1.22.0.12040       winget
Discord                      Discord.Discord                        0.0.309                          1.0.9002             winget
```

I am guessing thats the reason.

**Comment by iDolmatov** [comment]
It was previously discussed that the version displayed and the version number are not the same. There are even times when the commercial version number is different from the actual version number in the program itself.
Variations in the display of the version number. So either you have to teach winget to interpret the version numbers, or read the version number from the program file (exe, dll, etc), which will be specified with a relative path in the manifest.

I cooperate with the AIMP player team and at the moment I was only able to make a limitation so that it would not be possible to downgrade the version number when updating. When a forced downgrade occurs, the player stops working with newer databases.

**Comment by lordraiden** [comment]
Something similar happened to me.
I did a first upgrade --all this 2 apps where updated, after that version becomes unknown and it tries to update every time although it is already updated

![image](https://user-images.githubusercontent.com/17175395/120536159-1e1b5680-c3e4-11eb-9104-45f8db908be6.png)


![image](https://user-images.githubusercontent.com/17175395/120536293-3d19e880-c3e4-11eb-917c-bec07f5c9d1f.png)

**Comment by nlxdodge** [comment]
```bash
PS C:\Users\NLxDoDge> winget upgrade
Name                Id                              Version                Available    Source
----------------------------------------------------------------------------------------------
AIMP                AIMP.AIMP                       v4.70.2251, 23.05.2021 4.70.2251    winget
Battle.Net          Blizzard.BattleNet              Unknown                1.22.0.12040 winget
Bulk Rename Utility TGRMNSoftware.BulkRenameUtility Unknown                3.4.3.0      winget
Discord             Discord.Discord                 1.0.9000               1.0.9002     winget
MEGASync            Mega.MEGASync                   Unknown                4.5.1.0      winget
Mozilla Thunderbird Mozilla.Thunderbird             78.10.2                78.11.0      winget
GOG Galaxy          GOG.Galaxy                      Unknown                2.0.37.384   winget
Windscribe          Windscribe.Windscribe           2.2 Build 10           latest       winget
```
These are all packages that have issues on my personal system. Each of these is the latest version, but tries to update.
For example: Windscribe uses latest as a version and some software reports an Unkown version on my system. But I installed everything with Winget. 

Windows Package Manager v1.0.11451
Windows: Windows.Desktop v10.0.19043.1023
Package: Microsoft.DesktopAppInstaller v1.11.11451.0

**Comment by cheeseandjamsandwich** [comment]
I just experienced this issue.
It turned out that Blender and Teracopy that were repeatedly wanting to Upgrade each had two versions installed, listed in 'Apps and Features'.  The current version and a previous version.
Uninstalling the older versions fixed this.

**Comment by delirium-sidhe** [comment]
Found another package that updates infinitely:

`TechPowerUp GPU-Z TechPowerUp.GPU-Z Unknown 2.40.0    winget`

**Comment by toygark** [comment]
I have the same problem with Windscribe.

`Windscribe Windscribe.Windscribe 2.2 Build 10 latest         winget`

**Comment by krystofkrticka** [comment]
I also have this problem and I have it with Display Fusion installed from steam because in program and features there are two entries of display fusion one is for steam and the other one is for display fusion when installed normally.

![image](https://user-images.githubusercontent.com/37749100/122654178-d9b0ea00-d149-11eb-8cc9-1012aa73d504.png)

"DisplayFusion 9.8" is the entry which is also created by standard installer when installing display fusion from official website but that entry called just "DisplayFusion" without any numbers is created by steam but winget falsly detects the steam entry instead of standard entry.

**Comment by dennisvanderpool** [comment]
![image](https://user-images.githubusercontent.com/24899089/125998321-d0352bf6-8dd1-43d8-abe7-43b3f0bd2f3f.png)

I have same issue. Battle.Net keeps retrying due to the Unknown

**Comment by leochras** [comment]
I am also experiencing this issue..
![image](https://user-images.githubusercontent.com/16163571/126943194-29ce7f35-3a96-4bd2-9549-f82dc6878480.png)

**Comment by ImJoakim** [comment]
> I am also experiencing this issue..

@leochras https://github.com/microsoft/winget-cli/issues/1191#issuecomment-886416694

**Comment by denelon** [comment]
I believe we can address this with the v1.1 schema with multiple ARP entry support. The version in the manifest will be able to report a "marketing" version, but the ARP entry section can match what is actually installed.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/issues/1073#issuecomment-921870634

**Comment by ashpatil-msft** [comment]
This is similar to this issue: https://github.com/microsoft/winget-cli/issues/1105

**Comment by denelon** [comment]
I believe this has been addressed with Windows Package Manager 1.3.

Unknown versions are excluded from `winget upgrade --all`

Manifests can also now have AppsAndFeatures entries to allow a "marketing" version displayed for the user, but the upgrade comparison will be performed against the registry value for the software.

If this is not the case, then feel free to re-open the Issue and provide feedback.

**Comment by vaughan-naidoo** [comment]
This is still an issue. 

> winget upgrade --all
Name               Id                        Version     Available   Source
---------------------------------------------------------------------------
Amazon Kindle      Amazon.Kindle             2.0.1.70350 2.3.0.70673 winget
Vim 9.1 (x64)      vim.vim                   9.1.0       9.1.0312    winget
foobar2000 v1.6.16 PeterPawlowski.foobar2000 1.6.16      2.1.4       winget
MySQL Shell 8.1.1  Oracle.MySQLShell         8.1.1       8.2.0       winget
4 upgrades available.
1 package(s) have pins that prevent upgrade. Use the 'winget pin' command to view and edit pins. Using the --include-pinned argument may show more results.

Installing dependencies:
This package requires the following dependencies:
  - Packages
      Microsoft.VCRedist.2015+.x64
(1/3) Found Vim [vim.vim] Version 9.1.0312
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/vim/vim-win32-installer/releases/download/v9.1.0312/gvim_9.1.0312_x64.exe
  ██████████████████████████████  10.7 MB / 10.7 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(2/3) Found foobar2000 [PeterPawlowski.foobar2000] Version 2.1.4
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://www.foobar2000.org/files/foobar2000-x64_v2.1.4.exe
  ██████████████████████████████  6.48 MB / 6.48 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(3/3) Found MySQL Shell [Oracle.MySQLShell] Version 8.2.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://cdn.mysql.com/Downloads/MySQL-Shell/mysql-shell-8.2.0-windows-x86-64bit.msi
  ██████████████████████████████  60.9 MB / 60.9 MB
Successfully verified installer hash
Starting package install...
Successfully installed


> winget upgrade
Name               Id                        Version     Available   Source
---------------------------------------------------------------------------
Amazon Kindle      Amazon.Kindle             2.0.1.70350 2.3.0.70673 winget
Vim 9.1 (x64)      vim.vim                   9.1.0       9.1.0312    winget
foobar2000 v1.6.16 PeterPawlowski.foobar2000 1.6.16      2.1.4       winget
MySQL Shell 8.1.1  Oracle.MySQLShell         8.1.1       8.2.0       winget
4 upgrades available.
