### ISSUE TITLE
`winget upgrade --all` fails for all packages even if only one single package causes error

### ISSUE THREAD

**Issue by siddagra** [microsoft/winget-cli#1442]
# Brief description of your issue

If a single app fails to install in `winget upgrade --all`, it will close the entire upgrade sequence. Leaving all following apps unupgraded. Instead, it should upgrade all apps and ignore upgrading the apps for which an error occurs.
# Steps to reproduce

I Installed kite from vscode installer. Microsoft is unable to download the package/setup.exe and fails. It then does not proceed to upgrade/update any of my other apps:
![image](https://user-images.githubusercontent.com/52118936/132488000-9e07f1a7-ade6-471c-a7f5-422daffe2a62.png)

# Expected behavior
Winget should try to upgrade all apps and ignore upgrading the apps for which an error occurs.

# Actual behavior
If a single app fails to install in `winget upgrade --all`, it will close the entire upgrade sequence. Leaving all following apps unupgraded. 

# Environment

```none
[winget --info]
Windows Package Manager version: v1.0.11694
Windows: Windows 11
Package: App Installer                           Microsoft.DesktopAppInstaller_8wekyb3d8… 1.15.11694.0

Any other software?
```

**Comment by sba923** [comment]
I concur.

Just experienced the same thing:

````text
PS❯  winget upgrade
Name                                            Id                            Version        Available       Source
-------------------------------------------------------------------------------------------------------------------
Discord                                         Discord.Discord               1.0.9001       1.0.9004        winget
Microsoft Visual C++ 2008 Redistributable - x86 Microsoft.VC++2008Redist-x86  9.0.30729.4148 9.0.30729.6161  winget
Microsoft Windows Desktop Runtime - 5 (x86)     Microsoft.dotnetRuntime.5-x86 5.0.14.30911   5.0.15.31016    winget
GOG GALAXY                                      GOG.Galaxy                    Unknown        2.0.46.133      winget
Graphviz                                        Graphviz.Graphviz             2.38           2.50.0          winget
calibre                                         calibre.calibre               5.37.0         5.38.0          winget
Python 2                                        Python.Python.2               2.7.16150      2.7.18150       winget
VNC Viewer                                      RealVNC.VNCViewer             6.20.529.42646 6.21.1109.45988 winget
Go Programming Language                         GoLang.Go                     1.17.7         1.17.8          winget
Microsoft Visual Studio Code                    Microsoft.VisualStudioCode    1.64.2         1.65.2          winget
Microsoft .NET SDK                              Microsoft.dotnet              5.3.321.37723  6.1.322.12413   winget
Microsoft Windows Desktop Runtime - 5 (x64)     Microsoft.dotnetRuntime.5-x64 5.0.14.30911   5.0.15.31016    winget
Windows Assessment and Deployment Kit           Microsoft.WindowsADK          10.1.17134.1   10.1.22000.1    winget
Microsoft Windows Desktop Runtime - 6 (x86)     Microsoft.dotnetRuntime.6-x86 6.0.2.30914    6.0.3.31024     winget
14 upgrades available.
PS❯  winget upgrade --all
An unexpected error occurred while executing the command:
InternetOpenUrl() failed.
0x80072efd : unknown error
````

FWIW, here's my workaround:

````powershell
PS❯  winget upgrade | ConvertFrom-WingetStdout.ps1 | % { $_.Name; $_.Id; winget upgrade --id $_.Id }
````

using [ConvertFrom-WingetStdout.ps1](https://gist.github.com/sba923/7924b726fd44af91d18453ee595e6548).

**Comment by denelon** [comment]
@siddagra

I believe this has been resolved in a prior release. Can you confirm?

**Comment by JSkimming** [comment]
@siddagra A single error is still preventing me from upgrading all

```
winget upgrade --all
Found Graphviz [Graphviz.Graphviz] Version 2.50.0
Found OpenSSL Light [ShiningLight.OpenSSL.Light] Version 1.0.0
Found VLC media player [VideoLAN.VLC] Version 3.0.17
Found pgAdmin 4 [PostgreSQL.pgAdmin] Version 6.5
Found Node.js [OpenJS.NodeJS] Version 17.7.1
Found Microsoft .NET SDK [Microsoft.dotnet] Version 6.1.322.12413
Found Microsoft Windows Desktop Runtime - 3 (x64) [Microsoft.dotnetRuntime.3-x64] Version 3.1.23.31022
Found Jabra Direct [Jabra.Direct] Version 5.12.6601
Found Python 3 [Python.Python.3] Version 3.10.2150.0
Found GitHub CLI [GitHub.cli] Version 2.6.0
Found Microsoft SQL Server Management Studio [Microsoft.SQLServerManagementStudio] Version 15.0.18410.0
(1/11) Found Graphviz [Graphviz.Graphviz] Version 2.50.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://gitlab.com/api/v4/projects/4207231/packages/generic/graphviz-releases/2.50.0/windows_10_cmake_Release_graphviz-install-2.50.0-win64.exe
  ██████████████████████████████  4.48 MB / 4.48 MB
Successfully verified installer hash
Starting package install...
Successfully installed

(2/11) Found OpenSSL Light [ShiningLight.OpenSSL.Light] Version 1.0.0
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://slproweb.com/download/Win64OpenSSL_Light-1_1_1m.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

**Comment by sba923** [comment]
Related issue: if one of the updates is canceled (e.g. at a UAC prompt) the operation does not continue with the next update.

**Comment by psychelzh** [comment]
@denelon This has not been solved. 

```
winget upgrade --all
已找到 全球学术快报 [TTKN.CNKIExpress] 版本 0.1.19
已找到 Node.js [OpenJS.NodeJS] 版本 17.7.2
已找到 Microsoft .NET SDK [Microsoft.dotnet] 版本 6.1.322.12413
已找到 Telegram Desktop [Telegram.TelegramDesktop] 版本 3.6.1
已找到 calibre [calibre.calibre] 版本 5.39.1
已找到 GitHub CLI [GitHub.cli] 版本 2.6.0
已找到 Python 3 [Python.Python.3] 版本 3.10.3150.0
已找到 网易云音乐 [NetEase.CloudMusic] 版本 2.9.8.199759
已找到 钉钉 [Alibaba.DingTalk] 版本 6.3.35-Release.3179104
(1/9) 已找到 全球学术快报 [TTKN.CNKIExpress] 版本 0.1.19
此应用程序由其所有者授权给你。
Microsoft 对第三方程序包概不负责，也不向第三方程序包授予任何许可证。
Downloading https://download.cnki.net/cnkiexpress/%E5%85%A8%E7%90%83%E5%AD%A6%E6%9C%AF%E5%BF%AB%E6%8A%A5%20Setup%200.1.19.exe
执行此命令时发生意外错误：
Download request status is not success.
0x80190194 : δ�ҵ�(404)��
```

**Comment by JSkimming** [comment]
Several people have replied with feedback, can we remove the [Needs-Author-Feedback](https://github.com/microsoft/winget-cli/labels/Needs-Author-Feedback) label?

**Comment by denelon** [comment]
@JSkimming, the author reported this with the 1.0 release. This was corrected in a previous release. I've been able to cause a failure in one of the packages during `winget upgrade -all` and had the remaining installations continue. I believe this is resolved. None of the additional reports are showing which version of the Windows Package Manager they are using.

**Comment by JSkimming** [comment]
@denelon I can confirm that `winget upgrade --all` fails to continue after this particular failure on version [v1.2.10271](https://github.com/microsoft/winget-cli/releases/tag/v1.2.10271).

<details><summary>Show output</summary>

```
C:\Windows\system32>winget --version
v1.2.10271
C:\Windows\system32>winget upgrade --all
Found Microsoft Teams [Microsoft.Teams] Version 1.5.00.5967
(1/1) Found Microsoft Teams [Microsoft.Teams] Version 1.5.00.5967
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Successfully verified installer hash
Starting package install...
Installer failed with exit code: 1638
Installer log is available at: C:\Users\james\AppData\Local\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir\WinGet-Microsoft.Teams.1.5.00.5967-2022-03-28-16-21-40.833.log
Another version of this application is already installed.
```
</details>

![WingetUpgradeAll](https://user-images.githubusercontent.com/647706/160433261-313fa4f7-bc45-483f-b8cf-7c9616529fb4.gif)

**Comment by sba923** [comment]
> Related issue: if one of the updates is canceled (e.g. at a UAC prompt) the operation does not continue with the next update.

I have reproduced this with 1.2

**Comment by denelon** [comment]
@JSkimming Teams is known to be problematic with the system wide installer. We have other issues tracking that. I believe what was reported is when there are multiple upgrades, and one of them fails, the other upgrades don't even run.

There are still several challenges with upgrading individual applications, and we have several bugs open for those. This bug was specifically calling out the failure for `winget upgrade --all` to continue with the other packages after a single failure.

**Comment by denelon** [comment]
@sba923 I'll look into that scenario. Do you know which package had the UAC you cancelled? I'll set up a test to verify that situation.

**Comment by frederickjjoubert** [comment]
Any update on this? It's still happening:

```
PS C:\Windows\system32> winget upgrade --all
Name                                             Id                                    Version    Available Source
------------------------------------------------------------------------------------------------------------------
Visual Studio Community 2022                     Microsoft.VisualStudio.2022.Community 17.5.0     17.6.2    winget
Mozilla Firefox (x64 en-US)                      Mozilla.Firefox                       112.0      113.0.2   winget
OBS Studio                                       OBSProject.OBSStudio                  29.0.2     29.1.2    winget
TeamViewer                                       TeamViewer.TeamViewer                 15.39.5    15.42.6   winget
qBittorrent                                      qBittorrent.qBittorrent               4.5.1      4.5.2     winget
AOMEI Partition Assistant 9.14.0                 AOMEI.PartitionAssistant              9.14.0     10.0.0    winget
Microsoft Windows Desktop Runtime - 7.0.3 (x64)  Microsoft.DotNet.DesktopRuntime.7     7.0.3      7.0.5     winget
JetBrains ETW Host Service (x64)                 JetBrains.ReSharper                   > 2022.2.2 2022.3.3  winget
Microsoft .NET SDK 5.0.400 (x64)                 Microsoft.DotNet.SDK.7                < 7.0.100  7.0.302   winget
Microsoft .NET SDK 7.0.200 (x64)                 Microsoft.DotNet.SDK.7                7.0.200    7.0.302   winget
Microsoft Windows Desktop Runtime - 6.0.14 (x64) Microsoft.DotNet.DesktopRuntime.6     6.0.14     6.0.16    winget
11 upgrades available.
1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).
```

**Comment by fkoch-tgm** [comment]
Yeah, I also experience this issue with `v1.6.1573-preview`:
```
PS C:\WINDOWS\system32> winget upgrade -r
Name                                             Id                                     Version        Available      Source
----------------------------------------------------------------------------------------------------------------------------
Visual Studio Build Tools 2022                   Microsoft.VisualStudio.2022.BuildTools 17.6.4         17.6.5         winget
Google Chrome                                    Google.Chrome                          111.0.5563.148 114.0.5735.199 winget
maxima-5.41.0                                    MaximaTeam.Maxima                      5.41.0         5.46.0         winget
Maxima computer algebra system                   MaximaTeam.Maxima                      5.45.1         5.46.0         winget
Microsoft XNA Framework Redistributable 4.0      Microsoft.XNARedist                    4.0.20823.0    4.0.30901.0    winget
Webex                                            Cisco.WebexTeams                       42.11.0.24187  43.6.0.26407   winget
Microsoft Windows Desktop Runtime - 6.0.19 (x64) Microsoft.DotNet.DesktopRuntime.6      6.0.19         6.0.20         winget
Epic Games Launcher                              EpicGames.EpicGamesLauncher            1.3.67.0       1.3.78.0       winget
SharpKeys                                        RandyRants.SharpKeys                   3.9.0000       3.9.4000       winget
Eclipse Temurin JDK mit Hotspot 17.0.5+8 (x64)   EclipseAdoptium.Temurin.17.JDK         17.0.5.8       17.0.7.7       winget
Microsoft Windows Desktop Runtime - 7.0.8 (x64)  Microsoft.DotNet.DesktopRuntime.7      7.0.8          7.0.9          winget
13 upgrades available.

The following packages have an upgrade available, but require explicit targeting for upgrade:
Name                         Id              Version      Available   Source
----------------------------------------------------------------------------
Microsoft Teams              Microsoft.Teams 1.3.00.12058 1.6.00.6754 winget
Teams Machine-Wide Installer Microsoft.Teams 1.3.0.362    1.6.00.6754 winget
2 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
An unexpected error occurred while executing the command:
0x80190194 : Not found (404).
```

<details><summary>winget info</summary>
<pre>
PS C:\WINDOWS\system32> winget --info
Windows Package Manager (Preview) v1.6.1573-preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.23521.1000
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.21.1573.0

Winget Directories
-------------------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
</pre>
</details>
