### ISSUE TITLE
Spotify.Spotify does not install or update if winget is running in admin mode

### ISSUE THREAD

**Issue by bshoshany** [microsoft/winget-cli#1452]
Create issues related to the winget.exe client [here](https://github.com/microsoft/winget-cli/issues/new?template=Bug_Report.md)

# Brief description of your issue

I run `winget upgrade --all` to upgrade all packages automatically at startup. This has to be run in administrator mode, otherwise I need to manually click "Yes" in User Account Control for every single package that gets updated. However, when winget attempts to upgrade Spotify, the installer complains that it has to be installed using a normal account instead of an Administrator account (see screenshot). This not only means that it won't update, it also means it will stop the automated update at startup since I have to click "OK" in the dialog box before winget can continue.

![image](https://user-images.githubusercontent.com/61846320/132129332-30174463-54ec-42b3-83f7-dba4c0cec758.png)

# Steps to reproduce

1. Open administrator command prompt / powershell
2. Type `winget upgrade spotify`

Note that if Spotify is not already installed, then it also cannot be installed for the first time from admin mode:

1. Open administrator command prompt / powershell
2. Type `winget install spotify`

# Expected behavior

Spotify should install or upgrade in admin mode.

# Actual behavior

Spotify does not install or upgrade in admin mode.

# Environment

```none
Windows Package Manager v1.0.11692
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19043.1165
Package: Microsoft.DesktopAppInstaller v1.12.11692.0
```

# Suggestions for solution

* If Spotify has a different installer which works in both normal and admin mode, then that installer should be used by the package.
* If the Spotify installer has a flag that allows it to install in admin mode, then that flag should be used by the package.
* If winget has an option to run an installer in normal mode even though winget itself was run in admin mode, then this option should be used by the Spotify package.
* If winget does not have such an option, then that option should be added!

**Comment by denelon** [comment]
Related To:
* [ ] #1537
* [ ] microsoft/winget-pkgs/issues/29148

**Comment by arbitmcdonald** [comment]
+1 for the request. This would be a total game changer.

**Comment by denelon** [comment]
We've discussed unintended consequences of killing processes. It's not worth the risk to make this a default behavior. We may consider that as a "power user" feature, but today, we don't have a reliable mechanism to know which process or processes are running and what else might break for a user.

**Comment by arbitmcdonald** [comment]
> We've discussed unintended consequences of killing processes. It's not worth the risk to make this a default behavior. We may consider that as a "power user" feature, but today, we don't have a reliable mechanism to know which process or processes are running and what else might break for a user.

Interesting. Could it be perhaps work as an optional switch? `--aggressive` or `--force-upgrade` etc

**Comment by denelon** [comment]
Something like that would be the "power user" option, but we still need to know what process or processes to kill.

It reminds me of the good old days with "kill -9".

**Comment by jlssmt** [comment]
> Something like that would be the "power user" option, but we still need to know what process or processes to kill.
> 
> It reminds me of the good old days with "kill -9".

taskkill /IM "spotify.exe" /F

?

**Comment by denelon** [comment]
Some packages install services and an executable to interact with them. We would need to be enlightened about any processes related to the package. In the case of someone running a plugin for say "OBS Studio" they might be unhappy if they were to run upgrade on OBS Studio and kill some long encoding session they were running from another package that was leveraging it. That's the main kind of reason we are avoiding it.

If we enrich the manifest to include information about all processes, it could be technically possible to kill them, but we don't have anything like that in the manifest today. The other thing we've seen are silent installers that aren't quite smart enough to explicitly stop the program, but the interactive installer mode is.

**Comment by Trenly** [comment]
@denelon - I believe the elevation setting requirement has been resolved with #2126 and since it wont upgrade while running, that should be tracked by #1786 and closed by #2217 (once merged)

**Comment by denelon** [comment]
I agree with @Trenly and I've confirmed the manifest now includes [elevationProhibited](https://github.com/microsoft/winget-pkgs/blob/b7787ef1f3cb2e34b4ad10a8e1d3975e2ab6736e/manifests/s/Spotify/Spotify/1.1.91.824.g07f1e963/Spotify.Spotify.installer.yaml#L15).

**Comment by martukas** [comment]
This is still a problem:
```powershell
❯ winget install Spotify.Spotify
The installer cannot be run from an administrator context.
```
powershell version 7.3.3
winget version v1.4.10173
`winget show Spotify.Spotify` shows package version " 1.2.6.863.ge7902f05" which is same as on winget.run

**Comment by Trenly** [comment]
> This is still a problem:
> 
> ```powershell
> ❯ winget install Spotify.Spotify
> The installer cannot be run from an administrator context.
> ```
> 
> powershell version 7.3.3 winget version v1.4.10173 `winget show Spotify.Spotify` shows package version " 1.2.6.863.ge7902f05" which is same as on winget.run

Run the install command in a standard powershell terminal, and not one that was run as administrator

**Comment by martukas** [comment]
@Trenly I just reread the original ticket text here just to make sure I am not crazy. Isn't the whole point of this issue that this is not correct behavior, when all other packages deal with admin privileges just fine? Your last couple of comments seem to indicate some feature that was added to resolve this rather than closing of ticket with "won't fix"?

**Comment by Trenly** [comment]
> @Trenly I just reread the original ticket text here just to make sure I am not crazy. Isn't the whole point of this issue that this is not correct behavior, when all other packages deal with admin privileges just fine? Your last couple of comments seem to indicate some feature that was added to resolve this rather than closing of ticket with "won't fix"?

The Spotify installer itself prohibits being run in an administrative context, it isnt something that WinGet has control over. Its also not an accurate statement to say that all other packages deal with admin priveleges correctly because I know there are packages that require admin to install but only install to a user context. Just because Spotify is the first example of applications requiring they be run in the user context and not an admin context doesn’t mean other installers don’t also have the same requirement.

The feature already existed to indicate which contexts an installer allows - elevatesSelf, elevationRequired, and elevationProhibited. My previous comments were stating that the installer requirement of elevationProhibited was added to the manifest at winget-pkgs so that the user is informed about the elevation requirement when a Spotify install is requested from an admin context instead of causing the breaking prompt

**Comment by martukas** [comment]
Ok, the nuance of how a breaking prompt compares to some other refusal error message and how that's what the final adopted fix was about is not super obvious.

To reword what you said - winget has added a feature that allows for more granular/graceful control over how privilege checks are performed for packages like this, but it is now up to the managers of particular packages (like Spotify) to make use of it to result in sensible and non-frustrating behavior. Does that sound about right?

Probably worth adding **determined to not be a bug as described by original reporter** somewhere in here for other mortals that come wandering in.

**Comment by florian-obradovic** [comment]
> > This is still a problem:
> > ```powershell
> > ❯ winget install Spotify.Spotify
> > The installer cannot be run from an administrator context.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > powershell version 7.3.3 winget version v1.4.10173 `winget show Spotify.Spotify` shows package version " 1.2.6.863.ge7902f05" which is same as on winget.run
> 
> Run the install command in a standard powershell terminal, and not one that was run as administrator

I have a similar issue when I try to install Spotify via Intune in user context.
I'm aware that this is not a winget issue itself... It looks like Intune is somehow executing the install script in admin context if the user is in local administrator group, eve if install scope is set to user (in Intune).

![CleanShot 2024-02-27 at 18 42 45@2x](https://github.com/microsoft/winget-cli/assets/57985125/c5637cab-34f4-498e-8915-0116a878c744)


`**********************
Windows PowerShell transcript start
Start time: 20240227182432
Username: DOMAIN\florianObradovic
RunAs User: DOMAIN\florianObradovic
Configuration Name: 
Machine: VWIN11-KES01 (Microsoft Windows NT 10.0.22631.0)
Host Application: powershell.exe -windowstyle hidden -executionpolicy bypass -command .\install.ps1
Process ID: 6192
PSVersion: 5.1.22621.2506
PSEdition: Desktop
PSCompatibleVersions: 1.0, 2.0, 3.0, 4.0, 5.0, 5.1.22621.2506
BuildVersion: 10.0.22621.2506
CLRVersion: 4.0.30319.42000
WSManStackVersion: 3.0
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
**********************
Transcript started, output file is C:\Users\florianObradovic\AppData\Local\_MEM\Log\Spotify.Spotify-install.log
Das Installationsprogramm kann nicht in einem Administratorkontext ausgeführt werden.
**********************
Windows PowerShell transcript end
End time: 20240227182434
**********************`

**Comment by AdreKiseque** [comment]
I'm not sure I understand, what's the point of this change? The installation still fails all the same. Why not use the flag to have WinGet install the package without elevation as needed, instead of just spitting an error and moving on?

**Comment by realBryanPoole** [comment]
Can confirm that if you run Powershell NOT as admin, the update it will install witht he regular command, "winget upgrade --all"

At least, for me. Good luck.
