### ISSUE TITLE
Installer failed with exit code: 0x80070002 : The system cannot find the file specified.  (Microsoft.WingetCreate)

### ISSUE THREAD

**Issue by katdti** [microsoft/winget-cli#2228]
### Brief description of your issue

Result of installing WingetCreate is
Installer failed with exit code: 0x80070002 : The system cannot find the file specified.

### Steps to reproduce

Open powershell adminstrator cmd and execute:
    winget install Microsoft.WingetCreate --verbose-logs

### Expected behavior

Expected Microsoft.WingetCreate to be installed

### Actual behavior

Installation fails.
Log is showing [FAIL] D:  ...
PC does not have a drive D:
[WinGet-2022-06-08-15-25-02.762.log](https://github.com/microsoft/winget-cli/files/8861958/WinGet-2022-06-08-15-25-02.762.log)

### Environment

```shell
Windows Package Manager v1.2.10941
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19044.1706
Package: Microsoft.DesktopAppInstaller v1.17.10941.0

Logs: %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale
```

**Comment by ryfu-msft** [comment]
Hey @katdti, 

Thanks for filing this issue. It is hard for us to know exactly what went wrong without more information. The best way to do that is to file a bug via [Feedback Hub](https://aka.ms/winget-feedback). Once we get your report, we'll be able to dive into the logs further and identify the problem.

**Comment by denelon** [comment]
@katdti we've released a newer version of wingetcreate. Can you reproduce this error?

**Comment by katdti** [comment]
Problem still exists with wingetcreate 1.1.2 and winget v1.4.2161-preview

Sources:
```
C:\Users\knr>winget source list
Name   Argument
---------------------------------------------
winget https://cdn.winget.microsoft.com/cache

```
Logs from running the command 
`winget install Microsoft.WingetCreate --verbose-logs`
is attached:
[WinGet-2022-08-09-08-19-26.956.log](https://github.com/microsoft/winget-cli/files/9287476/WinGet-2022-08-09-08-19-26.956.log)

**Comment by denelon** [comment]
@ryfu-msft do you have a bug for this at wingetcreate or do you understand the problem well enough with this Issue to fix it here?

**Comment by katdti** [comment]
It is unclear if this is a winget problem or wingetcreate package problem. 
No - I have not a bug at microsoft/winget-create only a bug here at microsoft/winget-cli.

**Comment by denelon** [comment]
@katdti can you submit a  [Feedback Hub](https://aka.ms/winget-feedback) report so we get logs to dig into?

**Comment by katdti** [comment]
Feedback submitted via Feedback Hub again.

**Comment by denelon** [comment]
Thank you.
