### ISSUE TITLE
Adobe Acrobat Pro DC is recognize as Adobe Acrobat Reader DC

### ISSUE THREAD

**Issue by JohnJohn45** [microsoft/winget-cli#2353]
### Brief description of your issue

I have Adobe Acrobat Pro DC in my computer but winget recognize it as Reader version and want to upgrade it.

### Steps to reproduce

install Adobe Acrobat Pro DC x64 (not lastest build build) --> "winget upgrade" -->Adobe Acrobat DC is recognize as Reader and want to upgrade

### Expected behavior

install Adobe Acrobat Pro DC x64 (not lastest build build) --> "winget upgrade" --> no package to upgrade

### Actual behavior

-

### Environment

```shell
Windows 11 Pro
```

**Comment by denelon** [comment]
This looks like a false positive on matching.

It may be possible to fix the manifest so that false matches don't happen.
Have you tested this on Windows Package Manager 1.3 release candidate build?

What version of Windows Package Manager are you currently running?
`winget --info` provides the information.

Current manifest for reference:
https://github.com/microsoft/winget-pkgs/blob/master/manifests/a/Adobe/Acrobat/Reader/64-bit/22.001.20169/Adobe.Acrobat.Reader.64-bit.installer.yaml

**Comment by JohnJohn45** [comment]
Package: Microsoft.DesktopAppInstaller v1.17.11601.0

**Comment by OfficialEsco** [comment]
Would you mind downloading Revo Uninstaller which would give us a lot more information? (Portable is enough)
1. Open Revo Uninstall
2. Right click on Adobe Acrobat (whatever it says)
3. Click open Registry Key
4. Share the Registry Path (The last part is the most important), for example
  ```
  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{3746f21b-c990-4045-bb33-1cf98cff7a68}
  ```
5. Share the `Publisher`, `DisplayName` and `DisplayVersion`, for example (Or just take a screenshot of the whole folder)
  ```
  Publisher: Microsoft Corporation
  DisplayName: Microsoft Visual C++ 2015-2022 Redistributable (x64) - 14.32.31332
  DisplayVersion: 14.32.31332.0
  ```

**Comment by JohnJohn45** [comment]
After verification it seems I have the same  Registry Path and DisplayName,  as Adobe Reader.
After uninstall and intall lastest version, it seems OK. Now I have the same DisplayName but different Registry Path

**Comment by ViktorK78** [comment]
Same issue happened with me today (Feb 20, 2025) on Win 11 Pro.
Adobe Acrobat Pro 64-bit version 2024.005.20399 was recognized by winget as Acrobat Reader 64-bit.  
Windows Package Manager v1.9.25200

Acrobat registry info:
 `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{AC76BA86-1033-FFFF-7760-BC15014EA700}`

`Publisher: Adobe
DisplayName: Adobe Acrobat (64-bit)
DisplayVersion: 24.005.20399`

I put it on the pinned list as a workaround.

**Comment by archford-se** [comment]
I'm not sure this is fixed. This is also happening for us still. I install the Adobe version from the Adobe Admin Console via creating a package within that console. Winget is saying it's reader 64bit.

current winget version: 1.25.34

however, when i use `winget install adobe.acrobat.pro`. it will find it and update it, it appears

**Comment by gagnonraphael** [comment]
We still have the same problem. 
Acrobat Pro 25.1.20432.0 is recognized as Reader 25.001.20432

**Comment by HugsterGVB** [comment]
Hi everyone,

I'm also experiencing the same issue described here regarding Winget-CLI incorrectly identifying the installed Adobe Acrobat version.

Following up on the discussion, I wanted to share a potential way to differentiate between the versions, as outlined by Adobe. According to their documentation, the following registry key can be used to determine the installed package level:

HKEY_LOCAL_MACHINE\SOFTWARE\Adobe\Adobe Acrobat\DC\Installer\

The value to check is SCAPackageLevel.

You can find more details about this here: https://helpx.adobe.com/acrobat/kb/about-acrobat-reader-dc-migration-to-64-bit.html

Hopefully, this information is helpful in diagnosing and resolving this issue.

Thanks!

**Comment by ec-max** [comment]
Same issue here, winget reader install fails because it's pro that is installed.

**Comment by agret** [comment]
I have today installed the latest version of Adobe Acrobat Pro and it is being identified as Adobe Reader in "winget list"

Adobe Acrobat (64-bit)                       Adobe.Acrobat.Reader.64-bit

Here is a screenshot of the registry

<img width="1422" height="718" alt="Image" src="https://github.com/user-attachments/assets/a23389c7-cd12-4133-b6d6-88f08c7a0b03" />

<img width="1422" height="904" alt="Image" src="https://github.com/user-attachments/assets/f2f755c3-8099-40f9-bbcf-9330fa4ff496" />

**Comment by agret** [comment]
Pinging @denelon or @JohnJohn45 to re-open this issue.

**Comment by Nugorra** [comment]
This is still an issue @denelon @JohnJohn45 
Pin works as a workaround, but that is not a solution.  

In "winget list" it's  "Adobe Acrobat (64-bit) Adobe.Acrobat.Reader.64-bit",  "SCAPackageLevel" is 3 (as we know should be Adobe Acrobat, and 1 should be Adobe Acrobat Reader), and still winget trys to upgrade Adobe Acrobat Reader.
