### ISSUE TITLE
Publishing is down again (failed to update source)

### ISSUE THREAD

**Issue by infinitepower18** [microsoft/winget-cli#2718]
### Brief description of your issue

Same problem that previously occured #2666 has started again. And downloading the msix from https://cdn.winget.microsoft.com/cache/source.msix returns a 0kb file.

### Steps to reproduce

Run `winget source update`

### Expected behavior

winget should have updated successfully

### Actual behavior

Winget will attempt to update the source when running any command but will return the message `Failed in attempting to update the source: winget`. If you run `winget source update` it will respond with Cancelled

### Environment

```shell
Windows Package Manager v1.3.2691
Windows: Windows.Desktop v10.0.22621.819
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.18.2691.0
```

**Comment by mdanish-kh** [comment]
FYI: https://github.com/microsoft/winget-pkgs/issues/86160#issuecomment-1323964593

**Comment by Vzz1c** [comment]
+1

**Comment by simkoG** [comment]
+1

**Comment by M43R** [comment]
+1

**Comment by M43R** [comment]
```sh
winget source list
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
```
ResourceNotFoundThe specified resource does not exist.

**Comment by vtvy** [comment]
I have the same problem "Failed in attempting to update the source: winget". After following [this solution](https://github.com/microsoft/winget-pkgs/issues/86160#issuecomment-1326269423), Winget will work perfectly.

**Comment by mgthantzin** [comment]
Another workaround is to use a VPN. Use a location far from your current continent.

**Comment by simkoG** [comment]
> Another workaround is to use a VPN. Use a location far from your current continent.

I think this is not enough. I tried it with my PC from Europe and my US VPN. Same error both times. 

**EU IP address** 
```
> ping cdn.winget.microsoft.com

Pinging sni1gl.wpc.nucdn.net [152.199.21.175] with 32 bytes of data:
Reply from 152.199.21.175: bytes=32 time=20ms TTL=56
Reply from 152.199.21.175: bytes=32 time=17ms TTL=56
Reply from 152.199.21.175: bytes=32 time=16ms TTL=56
Reply from 152.199.21.175: bytes=32 time=18ms TTL=56

Ping statistics for 152.199.21.175:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 16ms, Maximum = 20ms, Average = 17ms

> winget upgrade

Failed in attempting to update the source: winget
Name                                    Id                               Version  Available Source
--------------------------------------------------------------------------------------------------
Firefox Developer Edition (x64 hu)      Mozilla.Firefox.DeveloperEdition 108.0    108.0b4   winget
Mozilla Thunderbird (x64 en-US)         Mozilla.Thunderbird              102.3.3  102.5.0   winget
TeamViewer                              TeamViewer.TeamViewer            15.29.4  15.36.6   winget
Azul Zulu JDK 17.36.13 (17.0.4), 64-bit Azul.Zulu.17.JDK                 17.36.13 17.36.15  winget
PowerShell 7.2.7.0-x64                  Microsoft.PowerShell             7.2.7.0  7.3.0.0   winget
5 upgrades available.
1 package has a version number that cannot be determined. Using "--include-unknown" may show more results.
```

**Change to US VPN** 
```
> ipconfig /flushdns

Windows IP Configuration

Successfully flushed the DNS Resolver Cache.

> ping cdn.winget.microsoft.com

Pinging sni1gl.wpc.nucdn.net [152.199.21.175] with 32 bytes of data:
Reply from 152.199.21.175: bytes=32 time=43ms TTL=41
Reply from 152.199.21.175: bytes=32 time=43ms TTL=41
Reply from 152.199.21.175: bytes=32 time=43ms TTL=41
Reply from 152.199.21.175: bytes=32 time=43ms TTL=41

Ping statistics for 152.199.21.175:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 43ms, Maximum = 43ms, Average = 43ms

> winget upgrade

Failed in attempting to update the source: winget
Name                                    Id                               Version  Available Source
--------------------------------------------------------------------------------------------------
Firefox Developer Edition (x64 hu)      Mozilla.Firefox.DeveloperEdition 108.0    108.0b4   winget
Mozilla Thunderbird (x64 en-US)         Mozilla.Thunderbird              102.3.3  102.5.0   winget
TeamViewer                              TeamViewer.TeamViewer            15.29.4  15.36.6   winget
Azul Zulu JDK 17.36.13 (17.0.4), 64-bit Azul.Zulu.17.JDK                 17.36.13 17.36.15  winget
PowerShell 7.2.7.0-x64                  Microsoft.PowerShell             7.2.7.0  7.3.0.0   winget
5 upgrades available.
1 package has a version number that cannot be determined. Using "--include-unknown" may show more results.
```

You can see that the IP of `cdn.winget.microsoft.com` (`152.199.21.175`) and the error (`Failed in attempting to update the source: winget`) are the same both times.

**Comment by simkoG** [comment]
My bad, that was my UK VPN previously, sorry. It is working if you connect to a VPN server far away from me.

**Comment by VincentJoshuaET** [comment]
When will this be fixed?

**Comment by denelon** [comment]
We believe we've found the root cause. We've triggered another purge to reset the cache endpoints and we're working with our CDN provider to ensure all regions are updated. We've got a production change schedule for Monday to hopefully address this permanently.

**Comment by MarcoPeraza** [comment]
This has been happening for almost (more than?) a month. This is very alarming. Is winget something that administrators can rely on?

**Comment by denelon** [comment]
We've gotten an update on the CDN endpoints. There were two endpoints that needed to be manually purged. We've been told these have been completed.

**Comment by MarcoPeraza** [comment]
Still not working for me.

`PS C:\Users\User\code\BoxSetup> winget source reset --force
Resetting all sources...Done
PS C:\Users\User\code\BoxSetup> winget source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled`

**Comment by MarcoPeraza** [comment]
Working now

**Comment by denelon** [comment]
All, we've had our CDN provider flush a couple of the pesky nodes that weren't getting updated, and we're purging after each publish run. This should have been resolved around 5:00 PM Pacific yesterday.

**Comment by simkoG** [comment]
@denelon It is fixed for me (Hungary, EU).

**Comment by efie45** [comment]
Still not working for me. Getting 0 byte file from the CDN in US. 

cdn.winget.microsoft.com resolves to `152.195.19.97` for me.

**Comment by R-Adrian** [comment]
i posted the issue #2807 referenced above and it was pointed out to me that there is already a pinned issue ... so i experimented a bit more with the info i found in here.

_(GitHub places the pinned issues OUTSIDE the list of current issues - i did not even notice it because it is placed in such a way that is confused with an advertising banner... and i developed a habit to ignore anything placed in such locations... thus the pinned issues area is usually ignored)_

i tried downloading the https://cdn.winget.microsoft.com/cache/source.msix  file with:
- **internet explorer: result = error INET_E_DOWNLOAD_FAILURE**
- MS Edge Chromium, result = downloads ok
- Google Chrome, result = downloads ok
- Mozilla Firefox, result = downloads ok
- **`winget upgrade --verbose-logs` command line (winget v1.4.3531), result = Failed in attempting to update the source: winget An error occurred in the secure channel support**

```
2022-12-28 21:26:41.640 [REPO] Source past auto update time [5 mins]; it has been at least 27870926 mins
2022-12-28 21:26:42.095 [FAIL] WindowsPackageManager.dll!00007FF89ECBBF22: ReturnHr(1) tid(3c90) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 21:26:42.096 [FAIL] WindowsPackageManager.dll!00007FF89EB43CF1: LogHr(2) tid(3c90) 80072F7D 
2022-12-28 21:26:42.096 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FF89ECC7451: (caller: 00007FF89EB906FE) LogHr(3) tid(3c90) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 21:26:42.096 [REPO] Source add/update failed, waiting a bit and retrying: winget
2022-12-28 21:29:45.049 [FAIL] WindowsPackageManager.dll!00007FF89ECBBF22: ReturnHr(2) tid(3c90) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 21:29:45.049 [FAIL] WindowsPackageManager.dll!00007FF89EB43CF1: LogHr(5) tid(3c90) 80072F7D 
2022-12-28 21:29:45.050 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(540)\WindowsPackageManager.dll!00007FF89ECC6A33: (caller: 00007FF89EA88B3D) LogHr(6) tid(3c90) 80072F7D     Msg:[winrt::hresult_error: An error occurred in the secure channel support] 

2022-12-28 21:29:45.050 [REPO] Failed to update source: winget

```
```
ping cdn.winget.microsoft.com

Pinging sni1gl.wpc.nucdn.net [152.199.21.175] with 32 bytes of data:
Reply from 152.199.21.175: bytes=32 time=6ms TTL=58
Reply from 152.199.21.175: bytes=32 time=6ms TTL=58
Reply from 152.199.21.175: bytes=32 time=6ms TTL=58
Reply from 152.199.21.175: bytes=32 time=5ms TTL=58

Ping statistics for 152.199.21.175:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 5ms, Maximum = 6ms, Average = 5ms
```


![image](https://user-images.githubusercontent.com/16319504/209863949-45425ce5-245a-4c43-9caa-65e3d50dde1c.png)

**Comment by denelon** [comment]
@R-Adrian thanks! That's some hepful information. I wonder if something with the user agent might be at play. I'll share this with the engineering team.

**Comment by R-Adrian** [comment]
i think i nailed it... the error message is almost correct.... it is a SChannel problem but is actually a problem with Windows (10? 22H2?) ... the operating system is not actually TLS 1.3 compliant and has to use TLS 1.2
The download via the modern browsers works because the browser handles TLS 1.3 internally... but internet explorer and winget rely on the OS to establish the TLS connection... which is not working.

I managed to reproduce the issue on another computer like this:

a) defined the registry key

```
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SecurityProviders\SCHANNEL\Protocols\TLS 1.3\Client]
"DisabledByDefault"=dword:00000000
"Enabled"=dword:00000001
```

b) rebooted the system

c) and then managed to cause the schannel winget error by simply enabling the TLS 1.3 checkbox in the Advanced Internet Options ( inetcpl.cpl ) while at the same time having the TLS 1.3 SChannel registry setting above.

![image](https://user-images.githubusercontent.com/16319504/209872759-aea1da6d-680a-4695-a7fd-d7274adbeeb7.png)


d) when the TLS 1.3 checkbox is disabled in inetcpl.cpl, even if the SChannel registry settings for TLS 1.3 client remain enabled the checkbox overrides the registry setting, and winget (and internet explorer) works again... but it uses TLS 1.2 connections

![image](https://user-images.githubusercontent.com/16319504/209873270-f80ff1c5-5828-4797-b0be-8780651893a1.png)

**Comment by R-Adrian** [comment]
P.S. found further support material, TLS 1.3 seems is not intended to be supported in Windows 10

https://learn.microsoft.com/en-us/windows/win32/secauthn/protocols-in-tls-ssl--schannel-ssp-

![image](https://user-images.githubusercontent.com/16319504/209876629-25da40b5-3fb3-4eb0-b1f4-56139e8d74bd.png)

**Comment by R-Adrian** [comment]
P.S. 2.. after sleeping on it.. i think this TLS 1.3 bug with Microsoft Azure connections might also be the reason for Windows Update and the Microsoft Store app itself randomly failing instantly when you open them during the past few months ... and then they start to mysteriously work again if you leave them alone for a few minutes without doing anything to them.

**Comment by BuzzwordChief** [comment]
I get the same error on Windows 11 Home 22H2.

```
C:\Users\DaveM>winget upgrade --verbose-logs
Failed in attempting to update the source: winget
```

cdn.winget.microsoft.com resolves to `152.199.21.175` for me.
winget version `v1.3.2691`

**Comment by R-Adrian** [comment]
> I get the same error on Windows 11 Home 22H2.

can you please try temporarily disabling TLS 1.3 from the Internet Options -> Advanced control panel and trying again with that?  (start->run-> inetcpl.cpl) Make sure TLS 1.2 remains enabled there.

**Comment by BuzzwordChief** [comment]
Does not seem to help:
![image](https://user-images.githubusercontent.com/11695209/210087579-cd57d7c3-d1ae-483f-8894-235ac3caf7fa.png)

Do I have to restart or anything?

**Comment by R-Adrian** [comment]
> Do I have to restart or anything?

Not sure how Win11 behaves here, i only had to restart when i enabled TLS 1.3 in registry for SChannel, not when using the control panel on Win10 22H2.

Maybe try completely disabling TLS 1.3 via the registry options for SChannel and then rebooting?

**Comment by R-Adrian** [comment]
Happy New Year, and i tried testing another thing...

- on Win 10, toggling TLS 1.3 on/off in inetcpl.cpl still causes winget errors when TLS is on
- according to Qualys SSL Labs  https://cdn.winget.microsoft.com appears to be serving DIFFERENT content depending on the connection being on TLS 1.2 or TLS 1.3 and also if SNI is negotiated or not negotiated.
https://www.ssllabs.com/ssltest/analyze.html?d=cdn.winget.microsoft.com

i cannot make SSLLabs analyze the European side of the CDN - SSLLabs does not let me select 152.199.21.175 and it auto-selects to the North America one, 152.195.19.97.. so i added that to my hosts file and tested again with that.

**result: Same error happens with winget and 152.195.19.97 present in the hosts file (on Windows 10 22H2)**

![image](https://user-images.githubusercontent.com/16319504/210165841-f61675bf-d616-4d74-9289-7466f04923b8.png)

![image](https://user-images.githubusercontent.com/16319504/210165979-298cd778-203e-41ad-93a5-e12d42814cba.png)

![image](https://user-images.githubusercontent.com/16319504/210166363-23b5c7f0-faeb-4959-8d1c-1b14f2cd9036.png)

**Comment by fluentmoheshwar** [comment]
+1 Solutions didn't work for me.

**Comment by denelon** [comment]
We've been working with our CDN provider to squash the nasty zero-byte file being cached and served. Is anyone still getting this problem? If you are, can you share the IP address you're hitting?

**Comment by R-Adrian** [comment]
TLS 1.3 error is still there - the first few tries are with TLS 1.3 enabled then it works after disabling it again.

![image](https://user-images.githubusercontent.com/16319504/214957636-bf6b0b16-59b5-442b-8e12-84a95311712c.png)

```
C:\WINDOWS\system32>ping cdn.winget.microsoft.com

Pinging sni1gl.wpc.nucdn.net [2606:2800:233:1cb7:261b:1f9c:2074:3c] with 32 bytes of data:
Reply from 2606:2800:233:1cb7:261b:1f9c:2074:3c: time=11ms
Reply from 2606:2800:233:1cb7:261b:1f9c:2074:3c: time=11ms
Reply from 2606:2800:233:1cb7:261b:1f9c:2074:3c: time=11ms
Reply from 2606:2800:233:1cb7:261b:1f9c:2074:3c: time=11ms

Ping statistics for 2606:2800:233:1cb7:261b:1f9c:2074:3c:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 11ms, Maximum = 11ms, Average = 11ms

```

**Comment by BuzzwordChief** [comment]
Yes, same error...

![image](https://user-images.githubusercontent.com/11695209/215037430-21b38bd5-d802-4663-96b7-7b83f7dd2530.png)

**Comment by sebaFlame** [comment]
+1 EU (Belgium)

**Comment by Tarrowren** [comment]
+1
```
C:\Users\tarro>ping cdn.winget.microsoft.com

Pinging sni1gl.wpc.nucdn.net [152.199.39.108] with 32 bytes of data:
Reply from 152.199.39.108: bytes=32 time=377ms TTL=50
Reply from 152.199.39.108: bytes=32 time=362ms TTL=50
Reply from 152.199.39.108: bytes=32 time=378ms TTL=50
Reply from 152.199.39.108: bytes=32 time=372ms TTL=50

Ping statistics for 152.199.39.108:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 362ms, Maximum = 378ms, Average = 372ms
```

**Comment by Hobart** [comment]
```
C:\>winget upgrade
Failed in attempting to update the source: winget
Failed when searching source; results will not be included: winget
No installed package found matching input criteria.

C:\>winget source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache

C:\>ping cdn.winget.microsoft.com

Pinging sni1gl.wpc.nucdn.net [152.195.19.97] with 32 bytes of data:
Reply from 152.195.19.97: bytes=32 time=5ms TTL=58
Reply from 152.195.19.97: bytes=32 time=5ms TTL=58
Reply from 152.195.19.97: bytes=32 time=5ms TTL=58
Reply from 152.195.19.97: bytes=32 time=5ms TTL=58

Ping statistics for 152.195.19.97:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 5ms, Maximum = 5ms, Average = 5ms
```

**Comment by skieast** [comment]
Same:
C:\Windows\System32>ping cdn.winget.microsoft.com

Pinging sni1gl.wpc.nucdn.net [2606:2800:11f:1cb7:261b:1f9c:2074:3c] with 32 bytes of data:
Reply from 2606:2800:11f:1cb7:261b:1f9c:2074:3c: time=16ms
Reply from 2606:2800:11f:1cb7:261b:1f9c:2074:3c: time=17ms
Reply from 2606:2800:11f:1cb7:261b:1f9c:2074:3c: time=21ms
Reply from 2606:2800:11f:1cb7:261b:1f9c:2074:3c: time=16ms

Ping statistics for 2606:2800:11f:1cb7:261b:1f9c:2074:3c:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 16ms, Maximum = 21ms, Average = 17ms

**Comment by KK-Designs** [comment]
I'm still getting the error:
![image](https://user-images.githubusercontent.com/71038229/218287681-68f831a0-ca6f-4eb5-90c4-b00a0faba602.png)

**Comment by mohitcv** [comment]
Looks like it might be related to an expired certificate. Get the following error when navigating to https://cdn.winget.microsoft.com/cache/source.msix

<img width="474" alt="image" src="https://user-images.githubusercontent.com/332558/218292907-4fd1d3d8-0451-45b9-8d2e-e1aa8264b63c.png">

**Comment by R-Adrian** [comment]
the expired certificate is actually a slightly different problem than the primary issue of this thread. Still related to the general CDN infrastructure problems tho.

```
-----BEGIN CERTIFICATE-----
MIIIVzCCBj+gAwIBAgITMwAqQugcrqvHO0PEswAAACpC6DANBgkqhkiG9w0BAQwF
ADBZMQswCQYDVQQGEwJVUzEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9u
MSowKAYDVQQDEyFNaWNyb3NvZnQgQXp1cmUgVExTIElzc3VpbmcgQ0EgMDUwHhcN
MjIwMjE3MDAyNTU2WhcNMjMwMjEyMDAyNTU2WjBvMQswCQYDVQQGEwJVUzELMAkG
A1UECBMCV0ExEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
b3Jwb3JhdGlvbjEhMB8GA1UEAxMYY2RuLndpbmdldC5taWNyb3NvZnQuY29tMIIB
IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEApKEJOklptsBt/bO/25MfIHta
hOX0b6Pl29wE5wmwTxo+k+xjxOMRMYa4NIdRap/SPn89Cxy1+Gu9G4tcwoNoz3t1
MgJasYX9jCzJ2xh+rSqiMOiDlA+4bpr/kmPJgBKBoSCp2qEwNP4IqBXtDJMFHimP
pC+gkb4O78Utpwd9axlW+ZW5FXm51zJw5p5zzTgAZecTjjinJkbqFxMfxEnb0Bbu
DxuvSOhQ5vUtYYCVxGMzn9xUC8bAg4rvF6LU8jDQqXa6MXoUz+ypXrOT9NymO/zi
xVh3AJ5daP11MJoY5Z8DWjNV0tu/9ma7skz2gkiYOcdpoLSI+v7/63Bor9jfsQID
AQABo4IEADCCA/wwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB3AK33vvp8/xDI
i509nB4+GGq0Zyldz7EMJMqFhjTr3IKKAAABfwUbbN0AAAQDAEgwRgIhALcqVaZw
KB2T6cggiOnWA2NK2jAzlve3g9YtS5duwn3HAiEAoiyQJSjAxKnhsAFTeqFgQ0sY
ry8/p6Ix4GHJ0C+MBX4AdQDoPtDaPvUGNTLnVyi8iWvJA9PL0RFr7Otp4Xd9bQa9
bgAAAX8FG20RAAAEAwBGMEQCIC5wxXoSv+GmdAj+G2g0pRNeeYMN31yBBvOP31r8
kqcfAiBiEW2B7WUuK6hBy1Es8fhyYmjrC47dHYgxlmixoV6dogB2AHoyjFTYty22
IOo44FIe6YQWcDIThU070ivBOlejUutSAAABfwUbbTIAAAQDAEcwRQIgGIq8mV//
8pqIAlzwMUTBeUxRHg61/wcMxRX29kf3ZWgCIQDJL0erqSxYAl32Ss1mXQjyuOWS
OkNDbkDCHijcmV8R+DAnBgkrBgEEAYI3FQoEGjAYMAoGCCsGAQUFBwMCMAoGCCsG
AQUFBwMBMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIe91xuB5+tGgoGdLo7Q
DIfw2h1dgoTlaYLzpz4CAWQCASMwga4GCCsGAQUFBwEBBIGhMIGeMG0GCCsGAQUF
BzAChmFodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jv
c29mdCUyMEF6dXJlJTIwVExTJTIwSXNzdWluZyUyMENBJTIwMDUlMjAtJTIweHNp
Z24uY3J0MC0GCCsGAQUFBzABhiFodHRwOi8vb25lb2NzcC5taWNyb3NvZnQuY29t
L29jc3AwHQYDVR0OBBYEFLerI7cj9smhQIsMg9lHQqlJMbpwMA4GA1UdDwEB/wQE
AwIEsDAjBgNVHREEHDAaghhjZG4ud2luZ2V0Lm1pY3Jvc29mdC5jb20wZAYDVR0f
BF0wWzBZoFegVYZTaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jcmwv
TWljcm9zb2Z0JTIwQXp1cmUlMjBUTFMlMjBJc3N1aW5nJTIwQ0ElMjAwNS5jcmww
ZgYDVR0gBF8wXTBRBgwrBgEEAYI3TIN9AQEwQTA/BggrBgEFBQcCARYzaHR0cDov
L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9Eb2NzL1JlcG9zaXRvcnkuaHRtMAgG
BmeBDAECAjAfBgNVHSMEGDAWgBTHspx/HOO4Wu/paBqoXZTBJlJqaDAdBgNVHSUE
FjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDQYJKoZIhvcNAQEMBQADggIBADRimlcV
/sTP4KBMXbonhX8nwS2GS9LSm01H6cNN+wwkOtgskEysf4t849YZC3al2mrcCIwm
rYOLbDVMjgWlveyOn7m+E+nbaNwcKO010p0uEGMsTdNxGernCBCgGI9Z5VXpp+2K
U12pfXr76FViTBseFZea4TuVIaALBrCsG7F5Xm0QpNhvYBOWao7gP29BPuLL7n95
E7wUxBKqXTsHGEbcCHRBodP0mvxLXuJm6ODeq3jscNCu+62bqzniwLojgpNwHLNv
EBTIGS7CkVIPC96A95eL8bc6yIkI0auHF30UsyD3hmMZTFZSGN/KDWZgQ80c7cjD
rlWV9V11nL5D535Ej7InGdEwyNt5SlIPJI1LsiXL+ISNb/bGL5z7ZPIyPf3yj6P+
UBePr6pRXxooQ+XzLtH1EUBRjQZWiU342vQMIIMv/Qm50mI/Py6YPy/o1+IZoAGn
RkU/ElG2MQnewvQljjfUjBqNT0Ob34TgHjvoNrbOy7OmfIpxbwQAC46EgkwtwI0W
tHgj9uJGs62DvuwLkP4ydxFMkgVOBA+Goq4NeUTNvLMg4T53EcpCSB5vRwvRvmQ5
5Rkw6zjDgY9LBYudFxfkbnHoZGMG8SQ5GmmuyQ4bLn9SHmnfmsolSWJMmM1YZ5+8
JUkUUWV1d80UIQoYPndp9xbrLlKssEQ7v11i
-----END CERTIFICATE-----
```

![image](https://user-images.githubusercontent.com/16319504/218293188-ec1ddb30-36cc-4c44-b283-95152f1bc8c7.png)

**Comment by denelon** [comment]
We're working to renew the certificate.
* https://github.com/microsoft/winget-cli/issues/2956

**Comment by fluentmoheshwar** [comment]
Fixed after uninstalling internet download manager.

**Comment by R-Adrian** [comment]
> Fixed after uninstalling internet download manager.

i do not have internet download manager installed (or ever had it) and can still reliably trigger the CDN bug on multiple WIndows 10 computers that i use (both at home and at the office) by simply force-enabling TLS 1.3 support (which is "experimental" in Windows 10).

Maybe Internet Download Manager was messing with the system TLS support in SChannel and uninstalling it just reconfigured SChannel back to the defaults?

**Comment by fluentmoheshwar** [comment]
> > Fixed after uninstalling internet download manager.
> 
> i do not have internet download manager installed (or ever had it) and can still reliably trigger the CDN bug on multiple WIndows 10 computers that i use (both at home and at the office) by simply force-enabling TLS 1.3 support (which is "experimental" in Windows 10).
> 
> Maybe Internet Download Manager was messing with the system TLS support in SChannel and uninstalling it just reconfigured SChannel back to the defaults?

Probably, Disabling TLS 1.3 didn't help

**Comment by bepstein111** [comment]
This issue just began a few days ago for me, about two days after reinstalling (but kept my personal files). Nothing suggested so far has helped =[

**Comment by fluentmoheshwar** [comment]
Update: It happened again but installing Cloudflare WARP solved the issue, I think the problem isn't with winget CDN, but my ISP (Grameenphone), because I'm having same issue with twitter and GitHub (sometimes).

**Comment by bepstein111** [comment]
Update:
My problem was solved. It was caused by installing Private Internet Access which automatically turned on it's "VPN Kill switch" not allowing any traffic to flow via windows built-in networking. Browsers worked fine though which is why I was confused. I turned off the kill switch and everything appears to work fine now.

**Comment by denelon** [comment]
Hey all, we've addressed the zero-byte file issue in the CDN.

Publishing has been working consistently since then, so I'm going to go ahead and close this issue.

We're aware there are users who are still having issues updating the source in some scenarios, so we'll deal with those on a more case by case basis.
