### ISSUE TITLE
[Package Issue]: Gyan.FFmpeg does not uninstall correctly

### ISSUE THREAD

**Issue by mstevens83** [microsoft/winget-cli#2949]
### Please confirm these before moving forward

- [X] I have searched for my issue and not found a work-in-progress/duplicate/resolved issue.
- [X] I have not been informed if the issue is resolved in a preview version of the winget client.

### Category of the issue

Other

### Brief description of your issue

Package Gyan.FFmpeg (v5.1.2) does not properly uninstall:
![image](https://user-images.githubusercontent.com/2787305/218076903-e1054d9e-6444-459d-870b-622a346a765f.png)

I'm `using --force` because otherwise it refuses to uninstall due to the package being supposedly modified, which is not the case. I even get this straight away after installing it fresh.

Notice I'm running this as Administrator because that also how I install it (due to microsoft/winget-pkgs#95349 / https://github.com/microsoft/winget-cli/issues/2909).

### Steps to reproduce

(As administrator:)
`winget install gyan.ffmpeg`
`winget uninstall gyan.ffmpeg` (complains about the package being modified, which is not the case)
`winget uninstall gyan.ffmpeg --force`

### Actual behavior

`%LOCALAPPDATA%\Microsoft\WinGet\Packages\Gyan.FFmpeg_Microsoft.Winget.Source_8wekyb3d8bbwe` and subfolder/files remain behind.

### Expected behavior

All files/folders related to package are gone.

### Environment

```shell
Windows Package Manager v1.4.10173
Windows: Windows.Desktop v10.0.22621.1105
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.19.10173.0


Gyan.FFmpeg v5.1.2
```

**Comment by mdanish-kh** [comment]
This has been fixed in WinGet [v1.5.1081-preview release](https://github.com/microsoft/winget-cli/releases/tag/v1.5.1081-preview) through PR https://github.com/microsoft/winget-cli/pull/3002

cc @denelon

**Comment by alexyo02** [comment]
Hi, still have the same problem on the latest version of Winget (1.6.2291-preview), on Windows 11 22h2. No matter what command I use, the process is stuck

**Comment by mdanish-kh** [comment]
@alexyo02 That is probably related to https://github.com/microsoft/winget-cli/issues/3279. There are a couple workarounds to fix the uninstall mentioned in that issue
