### ISSUE TITLE
[Misdetech of the version]: Microsoft.DotNet.DesktopRuntime.6

### ISSUE THREAD

**Issue by TheBossMagnus** [microsoft/winget-cli#3004]

**Comment by treysis** [comment]
Happens again. All my DesktopRuntime versions are recognized as ```Microsoft.DotNet.DesktopRuntime.6```.

**Comment by TheBossMagnus** [comment]
> Happens again. All my DesktopRuntime versions are recognized as `Microsoft.DotNet.DesktopRuntime.6`.

Same, bc it got updated

**Comment by de-served** [comment]
```
winget list Desktop
-----------------------------------------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 5.0.17 (x86)          Microsoft.DotNet.DesktopRuntime.6           < 6.0.5                 6.0.19   winget
Microsoft Windows Desktop Runtime - 8.0.0 Preview 5 (x86) Microsoft.DotNet.DesktopRuntime.Preview     8.0.0-preview.5.23302.2          winget
Microsoft Windows Desktop Runtime - 3.1.32 (x64)          Microsoft.DotNet.DesktopRuntime.6           < 6.0.5                 6.0.19   winget
Microsoft Windows Desktop Runtime - 6.0.19 (x86)          Microsoft.DotNet.DesktopRuntime.6           6.0.19                           winget
Microsoft Windows Desktop Runtime - 5.0.17 (x64)          Microsoft.DotNet.DesktopRuntime.6           < 6.0.5                 6.0.19   winget
Microsoft Windows Desktop Runtime - 8.0.0 Preview 5 (x64) Microsoft.DotNet.DesktopRuntime.Preview     8.0.0-preview.5.23302.2          winget
Microsoft Windows Desktop Runtime - 3.1.32 (x86)          Microsoft.DotNet.DesktopRuntime.6           < 6.0.5                 6.0.19   winget
Microsoft Windows Desktop Runtime - 7.0.8 (x86)           Microsoft.DotNet.DesktopRuntime.6           > 6.0.19                         winget
Microsoft Windows Desktop Runtime - 6.0.19 (x64)          Microsoft.DotNet.DesktopRuntime.6           6.0.19                           winget
Microsoft Windows Desktop Runtime - 7.0.8 (x64)           Microsoft.DotNet.DesktopRuntime.6           > 6.0.19                         winget
```

Same boat.

**Comment by MagicAndre1981** [comment]
> Happens again. All my DesktopRuntime versions are recognized as `Microsoft.DotNet.DesktopRuntime.6`.

I also see always an upgrade, but 6.0.20 is now latest 6 version:

```
C:\Windows\system32>winget upgrade
Name                                             ID                                Version Verfügbar Quelle
-----------------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 6.0.20 (x64) Microsoft.DotNet.DesktopRuntime.7 < 7.0.0 7.0.9     winget
```

List shows correct 6 and 7 identifier:

```
C:\Windows\system32>winget list dotnet
Name                                             ID                                Version Quelle
--------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 7.0.9 (x64)  Microsoft.DotNet.DesktopRuntime.7 7.0.9   winget
Microsoft Windows Desktop Runtime - 6.0.20 (x64) Microsoft.DotNet.DesktopRuntime.6 6.0.20  winget
```

But on a different Window 10 system it works fine

**Comment by FPSUsername** [comment]
```
C:\Users\FPSUs> winget list "Desktop Runtime"
Name                                             Id                                Version  Available Source
------------------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 6.0.20 (x64) Microsoft.DotNet.DesktopRuntime.6 6.0.20             winget
Microsoft Windows Desktop Runtime - 5.0.14 (x64) Microsoft.DotNet.DesktopRuntime.6 < 6.0.5  6.0.20    winget
Microsoft Windows Desktop Runtime - 3.1.23 (x64) Microsoft.DotNet.DesktopRuntime.6 < 6.0.5  6.0.20    winget
Microsoft Windows Desktop Runtime - 7.0.9 (x64)  Microsoft.DotNet.DesktopRuntime.6 > 6.0.20 7.0.9     winget
```
```
C:\Users\FPSUs> winget list dotnet
Name                                             Id                                Version Source
--------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 6.0.20 (x64) Microsoft.DotNet.DesktopRuntime.6 6.0.20  winget
Microsoft Windows Desktop Runtime - 7.0.9 (x64)  Microsoft.DotNet.DesktopRuntime.7 7.0.9   winget
```

Not sure why it defaults to 6 with pretty much the same command, except filtering on something different. The `winget list "Desktop Runtime"` is the same as whatever is shown in `winget upgrade`.

**Comment by MagicAndre1981** [comment]
After installing the .net8 Desktop Runtime, the issue is solved:

```
C:\Windows\system32>winget list runtime
Name                                             ID                                Version Quelle
--------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 8.0.0 (x64)  Microsoft.DotNet.DesktopRuntime.8 8.0.0   winget
Microsoft .NET Runtime - 6.0.25 (x64)            Microsoft.DotNet.Runtime.6        6.0.25  winget
Microsoft Windows Desktop Runtime - 7.0.14 (x64) Microsoft.DotNet.DesktopRuntime.7 7.0.14  winget
Microsoft Windows Desktop Runtime - 6.0.25 (x64) Microsoft.DotNet.DesktopRuntime.6 6.0.25  winget
```

**Comment by treysis** [comment]
@MagicAndre1981 Not really. It might not show available versions in this list, but running `winget upgrade` still shows them with updates available. Weird.

**Comment by MagicAndre1981** [comment]
>  It might not show available versions in this list, but running `winget upgrade` still shows them with updates available. Weird.

no, it shows nothing to upgrade as .net6 is now Microsoft.DotNet.DesktopRuntime.6,  .net7 is Microsoft.DotNet.DesktopRuntime.7 and  .net8 is Microsoft.DotNet.DesktopRuntime.8 so every version is now seperate.

**Comment by treysis** [comment]
For me it looks like this:

```
C:\>winget upgrade
Name                                             Id                                Version            Available          Source
-------------------------------------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 3.1.32 (x64) Microsoft.DotNet.DesktopRuntime.6 < 6.0.5            6.0.25             winget
Microsoft Windows Desktop Runtime - 8.0.0 (x64)  Microsoft.DotNet.DesktopRuntime.6 > 6.0.25           8.0.0              winget
Microsoft Windows Desktop Runtime - 5.0.17 (x64) Microsoft.DotNet.DesktopRuntime.6 < 6.0.5            6.0.25             winget
Microsoft Windows Desktop Runtime - 7.0.14 (x64) Microsoft.DotNet.DesktopRuntime.6 > 6.0.25           7.0.14             winget
4 upgrades available.

1 package(s) have version numbers that cannot be determined. Use --include-unknown to see all results.
```

**Comment by MagicAndre1981** [comment]
I'm using 1.6.3133 on Windows 10 22H2

**Comment by treysis** [comment]
How did you install .net8 runtime? Via winget?

**Comment by MagicAndre1981** [comment]
yes, I installed it after updating 6 and 7. And after this I ran `winget upgrade` to see if there are other updates and here I was supreised that it worked now.

**Comment by treysis** [comment]
I installed it after manually downloading the installer. Now, after installing again via winget I still get this:

```
Microsoft Windows Desktop Runtime - 3.1… Microsoft.DotNet.DesktopRuntime.8 < 8.0.0            8.0.0              winget
Microsoft Windows Desktop Runtime - 5.0… Microsoft.DotNet.DesktopRuntime.8 < 8.0.0            8.0.0              winget
Microsoft Windows Desktop Runtime - 7.0… Microsoft.DotNet.DesktopRuntime.8 < 8.0.0            8.0.0              winget
Microsoft Windows Desktop Runtime - 6.0… Microsoft.DotNet.DesktopRuntime.8 < 8.0.0            8.0.0              winget
```

So, there's a difference how you install it, clearly. This has also be mentioned in this thread. It will probably come back for you when updating via Windows Update.

Alas, the issue isn't resolved.

**Comment by treysis** [comment]
@MagicAndre1981 Interestingly, my workplace Windows 10 computer looks as clean as yours.

**Comment by MagicAndre1981** [comment]
> @MagicAndre1981 Interestingly, my workplace Windows 10 computer looks as clean as yours.

it worked on all PCs/VMs except 1 laptop. And here it suddenly worked after installing .net 8 . This whole matching is confusing

**Comment by mziehm** [comment]
I just had this weird behaviour, when trying to upgrade from 6.0.22 to 6.0.25.

winget upgrade
```
Name                                             Id                                Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 6.0.22 (x64) Microsoft.DotNet.DesktopRuntime.6 6.0.22         6.0.25         winget
Windows PC Health Check                          Microsoft.WindowsPCHealthCheck    3.6.2204.08001 3.7.2204.15001 winget
Microsoft .NET Core Runtime - 2.1.11 (x64)       Microsoft.DotNet.Runtime.3_1      < 3.1.25       3.1.32         winget
```
winget upgrade Microsoft.DotNet.DesktopRuntime.6
```
Found Microsoft .NET Windows Desktop Runtime 6.0 [Microsoft.DotNet.DesktopRuntime.6] Version 6.0.25
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://dotnetcli.azureedge.net/dotnet/WindowsDesktop/6.0.25/windowsdesktop-runtime-6.0.25-win-x64.exe
  ██████████████████████████████  54.7 MB / 54.7 MB
Successfully verified installer hash
Starting package install...
Successfully installed
```
winget upgrade
```
Name                                             Id                                Version        Available      Source
-----------------------------------------------------------------------------------------------------------------------
Microsoft Windows Desktop Runtime - 5.0.17 (x64) Microsoft.DotNet.DesktopRuntime.6 < 6.0.5        6.0.25         winget
Windows PC Health Check                          Microsoft.WindowsPCHealthCheck    3.6.2204.08001 3.7.2204.15001 winget
Microsoft .NET Core Runtime - 2.1.11 (x64)       Microsoft.DotNet.Runtime.3_1      < 3.1.25       3.1.32         winget
```

I seems to download the correct URL, at the Apps & features also shows the hopefully correct version:
![image](https://github.com/microsoft/winget-cli/assets/30479231/3ed97629-4d03-479a-8229-667297b1c0a6)

Not sure this fit here, if not please feel free to move this to a new issue if needed.

**Comment by hueldoeu** [comment]
i have this
![image](https://github.com/microsoft/winget-cli/assets/11273667/4dd5e654-6b69-4795-a4b6-a576ea568a58)
and since this post got very long i would like to know the final solution.

**Comment by hueldoeu** [comment]
> i have this ![image](https://private-user-images.githubusercontent.com/11273667/300268990-4dd5e654-6b69-4795-a4b6-a576ea568a58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0NTI4MTEsIm5iZiI6MTcwNjQ1MjUxMSwicGF0aCI6Ii8xMTI3MzY2Ny8zMDAyNjg5OTAtNGRkNWU2NTQtNmI2OS00Nzk1LWE0YjYtYTU3NmVhNTY4YTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI4VDE0MzUxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThmN2RmNjRkNWVkNDA3Njc1MmZmMTJjYzYwNzRkYmUwZDA1MDRiMjgyMjNlZDNmZmY1MGIyM2E2YTU0ZmQ0NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GLJkmWFpB9B059oZfjD2oQs9nS0aM0okVvwrD8RpKiQ) and since this post got very long i would like to know the final solution.

alright the winget uninstall Microsoft.DotNet.DesktopRuntime.6 didn't work the first time so i closed cmd and started again, had to click again on some yes and it's gone now. i know what that means, but seriously, who still needs .NET desktop runtime anyway?

**Comment by MagicAndre1981** [comment]
> but seriously, who still needs .NET desktop runtime anyway?

this is required to run .net 6 WinForms/WPF apps. If you only run cli tools you can use the normal .net runtime `Microsoft.DotNet.Runtime.6`

**Comment by hueldoeu** [comment]
> > but seriously, who still needs .NET desktop runtime anyway?
> 
> this is required to run .net 6 WinForms/WPF apps. If you only run cli tools you can use the normal .net runtime `Microsoft.DotNet.Runtime.6`

i will wait until some program begs me to install Microsoft.DotNet.DesktopRuntime.6 . there is version 8 already just like java 22 so i don't give a damn about ms products.

**Comment by PsyEng** [comment]
Running the following command, should solve the problem:
`winget install --moniker dotnet-desktop-6`
The following command, should also work:
`winget install --id Microsoft.DotNet.DesktopRuntime.6'

**Comment by treysis** [comment]
Nope. Unfortunately not.

**Comment by PsyEng** [comment]
> Nope. Unfortunately not.

If you´ve the problem with "Microsoft.DotNet.DesktopRuntime.8", then you should use "--id Microsoft.DotNet.DesktopRuntime.8" or "-moniker dotnet-desktop-8", instead of 6.

**Comment by treysis** [comment]
Well, apparently I had to uninstall first. And after reinstalling `dotnet-desktop-6` it solved it for all other conflicts as well. At least for now. I don't trust it completely.

**Comment by hueldoeu** [comment]
can someone paste the solution again plz?

**Comment by treysis** [comment]
Uninstall dotnet-desktop-6, reinstall dotnet-desktop-6.

**Comment by eabase** [comment]
Still the same problem. 
I wonder if it is related to: #4415 ?

**Comment by hueldoeu** [comment]
i'll skip it on unigetUI
