### ISSUE TITLE
P.S.A. Original CDN will be retired

### ISSUE THREAD

**Issue by denelon** [microsoft/winget-cli#3652]
We will be retiring the CDN used by earlier versions of WinGet.

Please upgrade to WinGet 1.6 or WinGet 1.7-preview (or later as new releases come out).

You can update "App Installer" via the Microsoft Store.
You can also use https://aka.ms/getwinget to install the latest available version.

>Note: The default behavior on a new Windows installation is to have the Microsoft Store check for updates and to install the latest version of WinGet. This should affect less than 2% of devices. WinGet can be updated by updating the App Installer in the Microsoft Store. It is also possible to run `winget install "App Installer" -s msstore --force` via the command-line.

New Windows installs (Azure Virtual Desktop for example) may have an earlier version of WinGet (delivered via App Installer) and they may not function correctly to download the default "winget" source. Updating the client to the latest version via the Microsoft Store, or GitHub will mitigate the issue.

Several users have reported issues with getting source updates to function after installing the latest version of WinGet. We're looking into the root cause.

If you run `winget source update --force` in an administrator terminal/shell it should resolve the issue.
If that doesn't work, try `powershell -command Add-AppxPackage https://cdn.winget.microsoft.com/cache/source.msix`

Latest Update:
CDN Migration is complete

**Comment by denelon** [comment]
Some users may see HTTP 429 Server Busy errors temporarily as we work on the CDN changes.

**Comment by denelon** [comment]
We're getting blocked messages from the CDN.
We're working on the issue.

<img width="248" alt="image" src="https://github.com/microsoft/winget-cli/assets/61799811/72028720-ff82-4d88-ad2e-2977db318aa3">

**Comment by denelon** [comment]
It should be back up now.

**Comment by paulkram** [comment]
Hi,
for me it is still broken using winget v1.5.2201 and winget source URL https://cdn.winget.microsoft.com/cache

Any updates?

**Comment by dan-mba** [comment]
I am getting occasional successes

When it succeeds, the log shows the following:
```
2023-09-26 10:33:57.597 [CORE] WinINet downloading from url: https://winget-cache-pme-cxfsgwfxarb8hwg0.z01.azurefd.net/cache/source.msix
2023-09-26 10:33:57.978 [CORE] Download completed.
```

When it fails, the log shows:
```
2023-09-26 12:28:38.062 [CORE] WinINet downloading from url: https://cdn.winget.microsoft.com/cache/source.msix
2023-09-26 12:28:38.320 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(127)\WindowsPackageManager.dll!00007FF9697E405E: (caller: 00007FF9697E44A9) Exception(2) tid(1830) 8A15002E 
2023-09-26 12:28:38.328 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(562)\WindowsPackageManager.dll!00007FF969A75F74: (caller: 00007FF969806B2F) LogHr(2) tid(1830) 8A15002E     Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(127)\WindowsPackageManager.dll!00007FF9697E405E: (caller: 00007FF9697E44A9) Exception(2) tid(1830) 8A15002E ] 

2023-09-26 12:28:38.328 [REPO] Failed to update source: winget
```

I am using WinGet, version [1.6.2631] on Windows 11

**Comment by denelon** [comment]
Can you share the response from https://cdn.winget.microsoft.com/cache/source.msix when this happens?

**Comment by paulkram** [comment]
Chrome and firefox are happy and can download it. Winget failes, saying it can't download it. Is there a possibility to get more details?

**Comment by mkstephenson** [comment]
I am also getting errors when attempting to update my winget sources, winget source update results in a cancelled for winget and the error log contains a lot of the following:
[FAIL] WindowsPackageManager.dll!00007FFAADFB30C2: ReturnHr(1) tid(2b34) 80072EE7     Msg:[winrt::hresult_error: The server name or address could not be resolved].

From the same Powershell Core console using Invoke-WebRequest, I get a 200 OK for https://cdn.winget.microsoft.com/cache/source.msix, so the DNS resolution seems to work fine outside of winget.

Running v1.7.2491-preview on Windows 10 from Germany.

**Comment by primeinc** [comment]
```
> winget source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache

> winget -v
v1.6.2631

> winget source update
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled
```
Getting the same error, browser says Service Unavailable 
The request is blocked.
20230926T233325Z-n49rqu44d57szba50635s1eqsw00000001kg00000001et9w

[WinGet-2023-09-26-19-28-18.552.log](https://github.com/microsoft/winget-cli/files/12732520/WinGet-2023-09-26-19-28-18.552.log)

**Comment by jozephbrasil** [comment]
@primeinc same here. Did you find a way to fix it?

**Comment by HenkPoley** [comment]
@dan-mba @primeinc I've written my solution to "Failed in attempting to update the source: winget" here: https://github.com/microsoft/winget-cli/issues/3525#issuecomment-1736846054

**Comment by vortex852456** [comment]
![image](https://github.com/microsoft/winget-cli/assets/4114781/b3227eff-f387-4f27-aaf3-f1a1526f2a5d)
![image](https://github.com/microsoft/winget-cli/assets/4114781/01342f50-1b11-481f-91a6-249c83497fdd)

Got this error since my first request this day...

**Comment by Lusiiky** [comment]
Since yesterday evening _(around 5pm - UTC+2)_, I've been getting the error `Failed in attempting to update the source: winget` whenever I try a command like `winget upgrade`.

Current Location: Dunkerque, France
_The problem doesn't seem to be present on my computers in Arlon, Belgium or Capellen, Luxembourg._

### Soures:
```
Nom     Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache
```

### Logs:
```
2023-09-27 09:26:00.429 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\MsixInfo.cpp(313)\WindowsPackageManager.dll!00007FFD55151415: (caller: 00007FFD552B65F4) Exception(1) tid(938) 8051100F 
2023-09-27 09:26:00.429 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(53)\WindowsPackageManager.dll!00007 FFD553E9136: (caller: 00007FFD552B2907) LogHr(1) tid(938) 8051100F Msg:[PreIndexedPackageInfo failed on primary location -- D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\MsixInfo.cpp(313)\WindowsPackageManager.dll!00007 FFD55151415: (caller: 00007FFD552B65F4) Exception(1) tid(938) 8051100F ] 

2023-09-27 09:26:00.459 [FAIL] WindowsPackageManager.dll!00007FFD553BFB12: ReturnHr(1) tid(938) 801901AD Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(52)\WindowsPackageManager.dll!00007 FFD553B6E0E: (caller: 00007FFD550FB960) Exception(2) tid(938) 801901AD ] 

2023-09-27 09:26:00.459 [FAIL] WindowsPackageManager.dll!00007FFD55155EE7: LogHr(2) tid(938) 801901AD 
2023-09-27 09:26:00.460 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(64)\WindowsPackageManager.dll!00007 FFD553E9193: (caller: 00007FFD552B2907) LogHr(3) tid(938) 801901AD Msg:[PreIndexedPackageInfo failed on alternate location -- winrt::hresult_error: The text associated with this error code could not be found]. 

2023-09-27 09:26:00.460 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(66)\WindowsPackageManager.dll!00007FFD552B6745: (caller: 00007FFD552B2907) Exception(3) tid(938) 8051100F 
2023-09-27 09:26:00.460 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007 FFD553E69B1: (caller: 00007FFD5529D6C2) LogHr(4) tid(938) 8051100F Msg:[D:\a\_work1\\s\external\pkg\src\sAppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(66)\WindowsPackageManager.dll!00007 FFD552B6745: (caller: 00007FFD552B2907) Exception(3) tid(938) 8051100F ] 

2023-09-27 09:26:00.460 [REPO] Source add/update failed, waiting a bit and retrying: winget
2023-09-27 09:26:02.498 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\MsixInfo.cpp(313)\WindowsPackageManager.dll!00007FFD55151415: (caller: 00007FFD552B65F4) Exception(4) tid(938) 8051100F 

2023-09-27 09:26:02.498 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(53)\WindowsPackageManager.dll!00007 FFD553E9136: (caller: 00007FFD552B2907) LogHr(5) tid(938) 8051100F Msg:[PreIndexedPackageInfo failed on primary location -- D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\MsixInfo.cpp(313)\WindowsPackageManager.dll!00007 FFD55151415: (caller: 00007FFD552B65F4) Exception(4) tid(938) 8051100F ] 

2023-09-27 09:26:02.672 [FAIL] WindowsPackageManager.dll!00007FFD553BFB12: ReturnHr(2) tid(938) 801901AD Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(52)\WindowsPackageManager.dll!00007 FFD553B6E0E: (caller: 00007FFD550FB960) Exception(5) tid(938) 801901AD ] 

2023-09-27 09:26:02.672 [FAIL] WindowsPackageManager.dll!00007FFD55155EE7: LogHr(6) tid(938) 801901AD 
2023-09-27 09:26:02.672 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(64)\WindowsPackageManager.dll!00007 FFD553E9193: (caller: 00007FFD552B2907) LogHr(7) tid(938) 801901AD Msg:[PreIndexedPackageInfo failed on alternate location -- winrt::hresult_error: The text associated with this error code could not be found]. 
2023-09-27 09:26:02.672 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(66)\WindowsPackageManager.dll!00007FFD552B6745: (caller: 00007FFD552B2907) Exception(6) tid(938) 8051100F 
2023-09-27 09:26:02.672 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(562)\WindowsPackageManager.dll!00007 FFD553E5F74: (caller: 00007FFD55176B2F) LogHr(8) tid(938) 8051100F Msg:[D:\a\_work1\\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(66)\WindowsPackageManager.dll!00007 FFD552B6745: (caller: 00007FFD552B2907) Exception(6) tid(938) 8051100F ] 

2023-09-27 09:26:02.672 [REPO] Failed to update source: winget
```

### Environment

```shell
Gestionnaire de package Windows v1.6.2631
Copyright (c) Microsoft Corporation. Tous droits réservés.

Windows: Windows.Desktop v10.0.22621.2361
Architecture du système : X64
Package : Microsoft.DesktopAppInstaller v1.21.2631.0

Répertoires Winget
-----------------------------------------------------------------------------------------------------------------------------------------
Journaux                                     %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir
Paramètres utilisateurs                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\settings.json
Répertoire des liens portables (utilisateur) %LOCALAPPDATA%\Microsoft\WinGet\Links
Répertoire des liens portables (ordinateur)  C:\Program Files\WinGet\Links
Racine de package portable (utilisateur)     %LOCALAPPDATA%\Microsoft\WinGet\Packages
Racine du package portable                   C:\Program Files\WinGet\Packages
Racine de package portable (x86)             C:\Program Files (x86)\WinGet\Packages
Téléchargements du programme d’installation  D:\Users\Lusiiky\Downloads

Liens
---------------------------------------------------------------------------------------------
Déclaration de confidentialité        https://aka.ms/winget-privacy
Contrat de licence                    https://aka.ms/winget-license
Avis de tiers                         https://aka.ms/winget-3rdPartyNotice
Page d’accueil                        https://aka.ms/winget
Conditions générales du Windows Store https://www.microsoft.com/en-us/storedocs/terms-of-sale

Paramètre administrateur                  État
---------------------------------------------------
LocalManifestFiles                        Désactivé
BypassCertificatePinningForMicrosoftStore Désactivé
InstallerHashOverride                     Désactivé
LocalArchiveMalwareScanOverride           Désactivé
```

**Comment by Diogo-Rossi** [comment]
I'm getting the same error as @Lusiiky, in 2 computers

**Comment by razvangoga** [comment]
Same here (Germany)

**Comment by maddindeiss** [comment]
Can confirm this, I have the same error as @Lusiiky

**Comment by TimKarsten** [comment]
> Current Location: Dunkerque, France
> _The problem doesn't seem to be present on my computers in Arlon, Belgium or Capellen, Luxembourg._

Same issue. My location is German, IP 88.69.183.xxx

I don't think it is the WinGet Version or that the entire CDN is down. We probably would see more tickets. Could it be that a specific mirror for a local IP range is the culprit?

**Comment by JustAnotherWinAdmin** [comment]
Same issue affecting multiple machines here in the UK.

**Comment by antoniogott** [comment]
Same issue in Brazil, multiple computers in different ISPs

**Comment by SlimGary** [comment]
Same in France

**Comment by denelon** [comment]
All, we're dealing with a global issue related to the CDN. We're actively working with the other teams to mitigate. We are also working on a set of improvements to WinGet 1.6 that we intend to update as soon as possible.

**Comment by denelon** [comment]
We have already updated some of the DNS and we'll be working on a secondary DNS entry so the client has a fail over. We're still working with the CDN and we're working on a separate infrastructure for a backup CDN. The client will roll over gracefully to the backup. More details will come as we make progress.

**Comment by jmwielandt** [comment]
Same issue on Chile. Multiple PCs on different cities :)

**Comment by Acrivec** [comment]
I've just installed new Windows on my friends computer having this issue. I've even reinstalled the windows thinking it was corrupted installation.
Now I've noticed that I experience this error on my PC as well.
It's either 404 (unconfigured azure server) when trying to access through browser, or request denied.

**Comment by jmwielandt** [comment]
```powershell
while ($true) {
if (-not (winget source update --name winget) -contains "Cancelado") {
  write-host "RESURECTED!`a"
}
start-sleep -seconds 120
}
```

i just made this script to be notified when winget comes back to life :3

**Comment by tryfresh** [comment]
i also reinstall windows.. i am fool

**Comment by denelon** [comment]
We're testing an update to WinGet 1.6 with some mitigations in place related to the CDN issues. This client will **not** resolve the issues with the CDN but it is a part of the solution and as it rolls out more broadly and is updated on more devices, it will help reduce the impact of the CDN issue overall.

As soon as we finish testing, we will begin publishing this at GitHub and the Microsoft Store.

**Comment by denelon** [comment]
We have also reduced the size of the source.msix "Microsoft.PreIndexed.Package". This new index is a slightly different schema with some other optimizations to reduce the overall size going forward.

With the current set of packages, the reduction is a bit over 50% in file size.

**Comment by denelon** [comment]
Publishing the new index with all the new manifests (part of our "rebuild" process) takes a few hours. I'll give an update when this has been successfully deployed.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/releases/tag/v1.6.2701

We're currently publishing the updated WinGet 1.6 to the Microsoft Store.

**Comment by denelon** [comment]
The new index has been published. It will start rolling through the CDN endpoints.

**Comment by denelon** [comment]
WinGet 1.6.2701 is now in the Microsoft Store.

**Comment by topia** [comment]
I'm using Insider build, and I encountered the same issue. Because that version was released [3 weeks ago](https://github.com/microsoft/winget-cli/releases/tag/v1.7.2491-preview), should I consider downgrading it to the stable version?
If you have a plan to release a new insider build to mitigate the problem, I would like to wait for it.

**Comment by denelon** [comment]
We're going to release a new WinGet 1.7-preview build with all these fixes. I'm expecting that to go out tomorrow.

**Comment by vadimas00** [comment]
Download the Doge Mining Pool app to mine Doge coin for your good future.

Use my referral code : *8LZBNS*

Check below link to download the app from Google Play


https://play.google.com/store/apps/details?id=com.mremote.dogcoin.cloude.server

2023 m. rugs. 28 d., kt 03:13, Demitrius Nelon ***@***.***>
rašė:

**Comment by xd003** [comment]
I also noticed that the environment variables are not getting added correctly or something. For instance i installed rclone though winget but running rclone says the term is not recognized. It has never happened in past. I hope the upcoming update will fix this issue as well

**Comment by topia** [comment]
> I also noticed that the environment variables are not getting added correctly or something. For instance i installed rclone though winget but running rclone says the term is not recognized. It has never happened in past. I hope the upcoming update will fix this issue as well

You said that rclone installed via winget does not work properly? If so, you should submit a separate bug report to the winget-pkgs repository. https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Issue-Bug&projects=&template=package_issue.yml&title=%5BPackage+Issue%5D%3A+Package.Identifer

**Comment by xd003** [comment]
> > I also noticed that the environment variables are not getting added correctly or something. For instance i installed rclone though winget but running rclone says the term is not recognized. It has never happened in past. I hope the upcoming update will fix this issue as well
> 
> You said that rclone installed via winget does not work properly? If so, you should submit a separate bug report to the winget-pkgs repository. https://github.com/microsoft/winget-pkgs/issues/new?assignees=&labels=Issue-Bug&projects=&template=package_issue.yml&title=%5BPackage+Issue%5D%3A+Package.Identifer

My bad, there was something wrong on my end, i fixed it. i thought it might be somehow caused by the winget unable to update issue, sorry for the confusion.

**Comment by BrandonWanHuanSheng** [comment]
It also failed. You can check Azure Front Door Service by using the link below. 
https://www.bing.com/search?pglt=41&q=How+to+check+Azure+frontdoor+services&cvid=6d81876a2c684353afff87b2793318d0&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBCTI2MTk0ajBqMagCALACAA&FORM=ANNTA1&PC=U531

**Comment by BrandonWanHuanSheng** [comment]
Only firefox and google chrome work but microsoft edge give me the request was blocked.

**Comment by denelon** [comment]
It looks like we need to make one more small modification to WinGet 1.6 and then I think we will be good to go with addressing some traffic spikes that seem to be affecting the CDN. If we can get that out in the next day or two, we will include that in the next WinGet 1.7-prevew. 

If it is going to take longer than that, we will go ahead and cut a 1.7 preview and then we'll make the small change for 1.6 and another 1.7.

I also wanted to say thank you to everyone for patience and understanding.

**Comment by denelon** [comment]
We're expecting a CDN outage tonight. Please upgrade to WinGet 1.6 latest release.

You will not receive an updated index on earlier clients when this happens. We weren't able to update the 1.7-preview yet. We're working on getting that update out ASAP.

**Comment by denelon** [comment]
We kicked off the build for WinGet 1.7-preview(2).
It will be updated here at GitHub and the https://aka.ms/getwingetpreview URL will be updated.
It will also be flighted to Windows Insider Dev & for WinGet Insiders.

**Comment by denelon** [comment]
WinGet 1.7-preview has been updated:
* https://github.com/microsoft/winget-cli/releases/tag/v1.7.2711-preview

We will have another release coming out for both WinGet 1.6 and WinGet 1.7-preview.

**Comment by denelon** [comment]
The latest releases have been published at GitHub and in the Microsoft Store.

The WinGet 1.6 GA version is App Installer 1.21.2721 (WinGet 1.6.2721).
The WinGet 1.7-preview version is App Installer 1.22.2722 (WinGet 1.7.2722-preview).

**Comment by phil-harmoniq** [comment]
I am still getting issues with this on the latest update of winget 1.6:

```
❯ winget -v
v1.6.2721
```

https://cdn.winget.microsoft.com/ is giving me a 404 in my browser.

**Comment by trparky** [comment]
> I am still getting issues with this on the latest update of winget 1.6:
> 
> ```
> ❯ winget -v
> v1.6.2721
> ```
> 
> https://cdn.winget.microsoft.com/ is giving me a 404 in my browser.

I'm getting the same thing. How the heck is this issue keep coming back to haunt us?

**Comment by mivsvit** [comment]
winget v1.6.2721and v1.7.2711-preview returning `Failed in attempting to update the source`.
CDN returning `403 Forbidden` when fetching ` https://cdn.winget.microsoft.com/cache/source.msix`

```
>winget upgrade
Failed in attempting to update the source: winget
```
```
>winget -v       
v1.6.2721
```
403 errors:
```
>curl -v https://cdn.winget.microsoft.com/cache/source.msix                                                                                                                                                                                     
*   Trying [2620:1ec:bdf::64]:443...
* Connected to cdn.winget.microsoft.com (2620:1ec:bdf::64) port 443 (#0)
* schannel: disabled automatic use of client certificate
* ALPN: offers http/1.1
* ALPN: server accepted http/1.1
* using HTTP/1.1
> GET /cache/source.msix HTTP/1.1
> Host: cdn.winget.microsoft.com
> User-Agent: curl/8.0.1
> Accept: */*
>
* schannel: server closed the connection
< HTTP/1.1 403 Forbidden
< Date: Thu, 05 Oct 2023 09:08:55 GMT
< Content-Type: text/html
< Content-Length: 1261
< Connection: close
< Cache-Control: no-store
< x-azure-ref: 20231005T090855Z-ppep7x16qx4h55s8mqu9yxtf2s00000000mg00000001aquw
< X-Cache: CONFIG_NOCACHE
```
Trying 1.7.2711-preview, same behaviour:
```
>winget -v     
v1.7.2711-preview
>winget upgrade
Failed in attempting to update the source: winget
```
From winget logs, also 403:
```
2023-10-05 10:16:03.095 [CORE] WinGet, version [1.7.2711-preview], activity [{1CD55F5C-972D-4C6E-80A4-80D59D4EABF5}]
2023-10-05 10:16:03.095 [CORE] OS: Windows.Desktop v10.0.22621.2283
2023-10-05 10:16:03.095 [CORE] Command line Args: winget  upgrade --verbose-logs
2023-10-05 10:16:03.095 [CORE] Package: Microsoft.DesktopAppInstaller v1.22.2711.0
2023-10-05 10:16:03.131 [CORE] Retrieving headers from url: https://cdn.winget.microsoft.com/cache/source.msix
2023-10-05 10:16:03.257 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(165)\WindowsPackageManager.dll!00007FF919685528: (caller: 00007FF9197E9E74) Exception(1) tid(8670) 80190193 Forbidden (403).

2023-10-05 10:16:03.257 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(176)\WindowsPackageManager.dll!00007FF91992398D: (caller: 00007FF9197E9C8D) LogHr(1) tid(8670) 80190193 Forbidden (403).
    Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(165)\WindowsPackageManager.dll!00007FF919685528: (caller: 00007FF9197E9E74) Exception(1) tid(8670) 80190193 Forbidden (403).
] 

2023-10-05 10:16:03.257 [REPO] Falling back to reading the package data
2023-10-05 10:16:03.295 [FAIL] WindowsPackageManager.dll!00007FF9198F9C72: ReturnHr(1) tid(8670) 80190193 Forbidden (403).
    Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(52)\WindowsPackageManager.dll!00007FF9198F0F6E: (caller: 00007FF91962B960) Exception(2) tid(8670) 80190193 Forbidden (403).
] 

2023-10-05 10:16:03.295 [FAIL] WindowsPackageManager.dll!00007FF919687627: LogHr(2) tid(8670) 80190193 Forbidden (403).

2023-10-05 10:16:03.295 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(128)\WindowsPackageManager.dll!00007FF9199238C9: (caller: 00007FF9197EB3F0) LogHr(3) tid(8670) 80190193 Forbidden (403).
    Msg:[PreIndexedPackageUpdateCheck failed on primary location -- winrt::hresult_error: Forbidden (403).] 

2023-10-05 10:16:03.295 [CORE] Retrieving headers from url: https://winget-cache-pme-cxfsgwfxarb8hwg0.z01.azurefd.net/cache/source.msix
2023-10-05 10:16:03.338 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(165)\WindowsPackageManager.dll!00007FF919685528: (caller: 00007FF9197E9E74) Exception(3) tid(8670) 80190193 Forbidden (403).

2023-10-05 10:16:03.338 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(176)\WindowsPackageManager.dll!00007FF91992398D: (caller: 00007FF9197E9CE8) LogHr(4) tid(8670) 80190193 Forbidden (403).
    Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\Downloader.cpp(165)\WindowsPackageManager.dll!00007FF919685528: (caller: 00007FF9197E9E74) Exception(3) tid(8670) 80190193 Forbidden (403).
] 

2023-10-05 10:16:03.339 [REPO] Falling back to reading the package data
2023-10-05 10:16:03.375 [FAIL] WindowsPackageManager.dll!00007FF9198F9C72: ReturnHr(2) tid(8670) 80190193 Forbidden (403).
    Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerCommonCore\HttpStream\HttpClientWrapper.cpp(52)\WindowsPackageManager.dll!00007FF9198F0F6E: (caller: 00007FF91962B960) Exception(4) tid(8670) 80190193 Forbidden (403).
] 

2023-10-05 10:16:03.375 [FAIL] WindowsPackageManager.dll!00007FF919687627: LogHr(5) tid(8670) 80190193 Forbidden (403).

2023-10-05 10:16:03.375 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(139)\WindowsPackageManager.dll!00007FF919923909: (caller: 00007FF9197EB3F0) LogHr(6) tid(8670) 80190193 Forbidden (403).
    Msg:[PreIndexedPackageUpdateCheck failed on alternate location -- winrt::hresult_error: Forbidden (403).] 

2023-10-05 10:16:03.375 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(141)\WindowsPackageManager.dll!00007FF9197E9D6A: (caller: 00007FF9197EB3F0) Exception(5) tid(8670) 80190193 Forbidden (403).

2023-10-05 10:16:03.375 [FAIL] D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\RepositorySource.cpp(53)\WindowsPackageManager.dll!00007FF919921BD1: (caller: 00007FF9197D51FD) LogHr(7) tid(8670) 80190193 Forbidden (403).
    Msg:[D:\a\_work\1\s\external\pkg\src\AppInstallerRepositoryCore\Microsoft\PreIndexedPackageSourceFactory.cpp(141)\WindowsPackageManager.dll!00007FF9197E9D6A: (caller: 00007FF9197EB3F0) Exception(5) tid(8670) 80190193 Forbidden (403).
] 
```

**Comment by ManjotB27** [comment]
Having the same issue as mivsvit on both winget v1.6.2721and v1.7.2711-preview
https://cdn.winget.microsoft.com/cache/ still seems to be down for us.

**Comment by lucianstuparu** [comment]
Having the same issue on winget v1.6.2721

```
winget source add --name winget --arg 'https://cdn.winget.microsoft.com/cache'
Adding source:
  winget -> https://cdn.winget.microsoft.com/cache
An unexpected error occurred while executing the command:
0x8051100f : unknown error
```

**Comment by denelon** [comment]
Hey all, we're still working on CDN related issues on the back end. We had a bit of a perfect storm with multiple loosely related issues, and a couple of unrelated issues at the same time. Several teams have been engaged and there are folks putting in extra time on the evenings and weekends here to try and get things back to smooth and stable.

I've seen reports of the zero-byte file rearing up again. We were able to reproduce last night around 11:00 PM. We haven't seen this in quite some time so we're working with our CDN partner to see what changed.

We've had throttling on some of the CDN regions continue to block traffic for failing to honor HTTP 429 retry-after requests. A new client build is coming out with that in it (both 1.6 and 1.7-preview).

We got a report of a regression in App Installer related to External Dependencies. That fix will be included in the client updates mentioned above.

We've gotten reports of performance issues with the WinGet COM server on some devices, and we believe this is related to an integration via our COM APIs that also seems to correlate with some of the increased traffic we've seen causing spikes (leading to the 429 responses).

We will continue working on the back end with our CDN provider, the client updates to mitigate some of the other behaviors we've seen and addressing critical bugs (most likely a regression) that have been reported.

**Comment by denelon** [comment]
https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released.
It is in the certification stage for the Microsoft Store.

**Comment by thuannguy** [comment]
Can I ask what exactly this new release fix? I still get:

``
Updating all sources...
Updating source: msstore...
Done
Updating source: winget...
Cancelled
``

**Comment by trparky** [comment]
> https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released. It is in the certification stage for the Microsoft Store.

I manually installed the release that you mentioned but the Windows Store keeps wanting to install version 1.7.2722-preview. Why? How can I prevent the Store from installing the preview version?

**Comment by xd003** [comment]
I am still getting the error as below
```Failed in attempting to update the source: winget```

**Comment by mivsvit** [comment]
> Can I ask what exactly this new release fix? `

It adds functionality to respect a "429 retry after" response from the CDN for cases when the CDN says it is too busy. 
See

https://github.com/microsoft/winget-cli/commit/e9b25d4ec0d15f7e33a8ea96f63105906b9b1839

**Comment by MichaelReiserSAP** [comment]
Interestingly we are facing the WinGet CDN error in India/Bangalore but not in EMEA/Germany

**Comment by mivsvit** [comment]
> Interestingly we are facing the WinGet CDN error in India/Bangalore but not in EMEA/Germany

I believe that is expected as per @denelon's earlier comment:
"We've had throttling on some of the CDN regions continue to block traffic for failing to honor HTTP 429 retry-after requests".

**Comment by MichaelReiserSAP** [comment]
> > Interestingly we are facing the WinGet CDN error in India/Bangalore but not in EMEA/Germany
> 
> I believe that is expected as per @denelon's earlier comment: "We've had throttling on some of the CDN regions continue to block traffic for failing to honor HTTP 429 retry-after requests".

OK didn't see this one, thanks!

**Comment by denelon** [comment]
> > https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released. It is in the certification stage for the Microsoft Store.
> 
> I manually installed the release that you mentioned but the Windows Store keeps wanting to install version 1.7.2722-preview. Why? How can I prevent the Store from installing the preview version?

Which version of Windows are you on?

**Comment by trparky** [comment]
> > > https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released. It is in the certification stage for the Microsoft Store.
> > 
> > 
> > I manually installed the release that you mentioned but the Windows Store keeps wanting to install version 1.7.2722-preview. Why? How can I prevent the Store from installing the preview version?
> 
> Which version of Windows are you on?

Windows 11, 22H2 (OS Build 22621.2361).

**Comment by denelon** [comment]
> > > > https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released. It is in the certification stage for the Microsoft Store.
> > > 
> > > 
> > > I manually installed the release that you mentioned but the Windows Store keeps wanting to install version 1.7.2722-preview. Why? How can I prevent the Store from installing the preview version?
> > 
> > 
> > Which version of Windows are you on?
> 
> Windows 11, 22H2 (OS Build 22621.2361).

Did you sign up for the Windows Package Manager Insider program?

**Comment by trparky** [comment]
> > > > > https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released. It is in the certification stage for the Microsoft Store.
> > > > 
> > > > 
> > > > I manually installed the release that you mentioned but the Windows Store keeps wanting to install version 1.7.2722-preview. Why? How can I prevent the Store from installing the preview version?
> > > 
> > > 
> > > Which version of Windows are you on?
> > 
> > 
> > Windows 11, 22H2 (OS Build 22621.2361).
> 
> Did you sign up for the Windows Package Manager Insider program?

How do I know if I did that? And if I did, how do I opt out of it?

**Comment by denelon** [comment]
CDN Migration is in progress. 

We're watching "real-time" traffic.

A new preview build with the honor 429 retry-after is out and is working its way through the Microsoft Store.
https://github.com/microsoft/winget-cli/releases/tag/v1.7.2782-preview

**Comment by denelon** [comment]
> > > > > > https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released. It is in the certification stage for the Microsoft Store.
> > > > > 
> > > > > 
> > > > > I manually installed the release that you mentioned but the Windows Store keeps wanting to install version 1.7.2722-preview. Why? How can I prevent the Store from installing the preview version?
> > > > 
> > > > 
> > > > Which version of Windows are you on?
> > > 
> > > 
> > > Windows 11, 22H2 (OS Build 22621.2361).
> > 
> > 
> > Did you sign up for the Windows Package Manager Insider program?
> 
> How do I know if I did that? And if I did, how do I opt out of it?

Use the same form from the "sign-up" for opt-out:
https://github.com/microsoft/winget-cli#development-releases

**Comment by trparky** [comment]
> > > > > > > https://github.com/microsoft/winget-cli/releases/tag/v1.6.2771 has been released. It is in the certification stage for the Microsoft Store.
> > > > > > 
> > > > > > 
> > > > > > I manually installed the release that you mentioned but the Windows Store keeps wanting to install version 1.7.2722-preview. Why? How can I prevent the Store from installing the preview version?
> > > > > 
> > > > > 
> > > > > Which version of Windows are you on?
> > > > 
> > > > 
> > > > Windows 11, 22H2 (OS Build 22621.2361).
> > > 
> > > 
> > > Did you sign up for the Windows Package Manager Insider program?
> > 
> > 
> > How do I know if I did that? And if I did, how do I opt out of it?
> 
> Use the same form from the "sign-up" for opt-out: https://github.com/microsoft/winget-cli#development-releases

OK, I did that. I'm assuming that it's not immediate. Right?

**Comment by RReverser** [comment]
I'm on winget v1.6.2771 which I believe is latest and can't re-add winget source (after previously resetting it as per recommendation from other users in linked issues):

```
C:\Users\me> winget source add --name winget --arg https://cdn.winget.microsoft.com/cache
Adding source:
  winget -> https://cdn.winget.microsoft.com/cache
An unexpected error occurred while executing the command:
0x801901a0 : unknown error

C:\Users\me> winget source list
Name    Argument
-----------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
```

I can download source.msix just fine but opening it manually fails with:

![image](https://github.com/microsoft/winget-cli/assets/557590/487b8dd1-16d0-4f85-8db4-b370e0763e9f)

Any ideas on next steps to try?

**Comment by RReverser** [comment]
> I can download source.msix just fine, no 429 or anything suspicious like that, but opening it manually fails with:

Ah interesting, looks like it downloads "successfully" and I can confirm with `curl` that server returns HTTP 200 OK, but the downloaded file is 0 bytes.

**Comment by mivsvit** [comment]
See https://github.com/microsoft/winget-cli/issues/3744
CDN is currently returning a 416 error " Requested range not satisfiable" to winget.

**Comment by RReverser** [comment]
> See #3744

Yeah looks like the same issue (note it was posted couple of hours later).

**Comment by denelon** [comment]
@RReverser try running `winget source reset --force` in administrator mode to reset the default sources.

We're looking into the zero-byte file issue.

**Comment by sspears1** [comment]
It appears that System context installs using the [Microsoft.WinGet.Client](https://www.powershellgallery.com/packages/Microsoft.WinGet.Client/0.2.1) PowerShell module no longer appear to be working after this change. 

`"%ProgramFiles%\PowerShell\7\pwsh.exe" -MTA --command Install-WinGetPackage` now returns the error message `Install-WinGetPackage: An error occurred while connecting to the catalog.`. This only occurs when trying to use the System user context. Normal user context installs are working as normal. 

This was working as expected for us the last few weeks using these instructions: https://github.com/microsoft/winget-cli/issues/3049#issuecomment-1613880312

The WinGet version being used is 1.6.2771.

**Comment by lucianstuparu** [comment]
For me it now works fine "winget source update" => "Updating source:
winget... 100%"

**Comment by aleksmelnyk** [comment]
After updating powershell to latest version (7.3.8) and reset sources, works fine.

**Comment by tchtrong** [comment]
As of today, I still cannot install packages using winget. I tried `winget source reset --force`, `winget source update` multiple times for the past few days and still no result. Hope the situation would be fixed soon.

**Comment by shalinikhare27** [comment]
@denelon - I ran the following:
1. `powershell -command Add-AppxPackage https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle` - This fetches the latest winget version. The output of running `winget --version` is `v1.6.2771`

2. `winget source list`
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0
winget  https://cdn.winget.microsoft.com/cache

3. `winget install --id Microsoft.Git --disable-interactivity --accept-source-agreements --accept-package-agreements` - This failed with the following error:
Failed when searching source: winget
An unexpected error occurred while executing the command: 
0x8a15000f : Data required by the source is missing
No packages were found among the working sources.

These commands are run on Windows 10. This thread mentions installing the latest version of winget will solve the problem, but in my case I do have the latest version and it is still throwing this error.

How I fixed:
I ran `powershell -command Add-AppxPackage https://cdn.winget.microsoft.com/cache/source.msix` before running the git install step and then it magically worked.

Questions:
1. Do we need to add the powershell command for `https://cdn.winget.microsoft.com/cache/source.msix` adding winget source for machines with latest winget versions as well?
2. Is there any correlation to CDN retirement that can cause the issue with newer winget versions as well?

**Comment by cvladan** [comment]
OMG.
Was it so hard to give better message than "Cancelled"?

https://github.com/microsoft/winget-cli/issues/1656

Dear Microsoft, you became a joke... so do your datacenter-corporate-bullshit and please, please just pay open-source project authors to do things efficiently - scoop.

**Comment by metayan** [comment]
Thank you, @shalinikhare27 , for
```
powershell -command Add-AppxPackage https://cdn.winget.microsoft.com/cache/source.msix
```

This fixed the
`Failed in attempting to update the source: winget`
error, that has been pestering me for a long time.

**Comment by daniatic** [comment]
I came here from #1656 and none of the solutions here worked, but I found a solution, I want to share, that also could give some insights into the origin of my problem and maybe similar problems of others.

Winget and Teams simultaneously did not work starting from today. Winget having the problem with the source as described thouroughly above and in the other thread, and Teams (New) was nearly reacting, couldn't send or receive messages and showed the following message in the top: We’ve run into a server error. Some functions might not work right now but you can continue to use the app. Even the Microsoft Store App told me I was offline and was unable to operate. Looking for a solution especially regarding teams I cam across following thread: https://answers.microsoft.com/en-us/msteams/forum/all/new-teams-weve-run-into-a-sever-error-every-day/275e8bb1-d260-4f06-a4e1-7eaa19852e35?page=3 and the last proposed solution to change Windows Internet Properties -> Connections -> LAN Settings -> Automatic Configuration and setting "Automatically detect settings", resolved all issues. Teams, winget and the Microsoft Store worked as nothing ever has happenend.

**Comment by StevieLamb** [comment]
@daniatic the "Automatically detect settings" can be a very risky option, particularly for "mobile" computers.

This instructs the computer to use the WPAD protocol, which can lead to disclosure of credentials to third parties, MitM attacks etc.

Evaluate the need to use this option very carefully before using it.

**Comment by daniatic** [comment]
@StevieLamb thank you very much for this information!

I will try turning it off again and hope that Teams and winget keep working. 

Do you have any ideas why this setting could affect the proper workings of these two apps?

**Comment by StevieLamb** [comment]
@daniatic I'm somewhat confused it was suggested as a resolution to you, and that it in fact helped you: that setting should only be useful if:
>  you are on a network with a proxy
>  the proxy supports auto-discovery

If these things are true for you then at least it makes some sense, but in that event I'd recommend talking to whoever administers the proxy about how it should be configured so you can avoid using WPAD.

If these things are **not** true then I'm afraid I'm stumped as to why enabling this setting fixed your issue.

**Comment by daniatic** [comment]
Then we stay in the dark... This is my private notebook and I used it in my private home network, where there is no proxy or similar. Even in the office there is no proxy of which I know of. No matter where I was these days it did not work until I changed that setting and without restart or any other intervention it just worked afterwards.

I disabled it the moment you told me and for now it still works.

**Comment by datdeep** [comment]
I cannot run “winget upgrade” or “winget source update”. They all return an error or fail with a cancel status when I try to update the winget source.

After I turn on WARP (you can download it at  [cloudflarewarp](https://cloudflarewarp.com/)), I can run “winget source update” and then “winget upgrade” and all winget commands run normally. I think you can use any VPN app. But with a free VPN app like WARP, we cannot choose which server or country to use, so it just randomly works sometimes and sometimes it does not.

Then I release that, when I do not turn on WARP VPN, if I ping cdn.winget.microsoft.com, it will ping 127.0.0.1 (I don’t know why). Even if I run ipconfig /flushdns, it still pings to 127.0.0.1. But when I turn on WARP VPN and ping cdn.winget.microsoft.com, it pings to another IP address than 127.0.0.1.

So, I edit the host file and add “152.199.21.175 cdn.winget.microsoft.com”. All winget commands work fine without turning on WARP.

I hope this helps if you cannot fix the source error by using all other advice.

You can use this PowerShell command to add a host entry:

```sh
# Get the path of the host file
$file = "C:\Windows\System32\drivers\etc\hosts"

# Get the content of the host file as a string
$hostfile = Get-Content $file

# Append the entry to the host file
$hostfile += "152.199.21.175 cdn.winget.microsoft.com"

# Set the content of the host file back to disk
Set-Content -Path $file -Value $hostfile -Force
```

**Comment by b1t3z3r0** [comment]
Guys, i was getting a "" and the only way i managed to have winget working properly was by following this exact steps from Microsoft:
https://learn.microsoft.com/en-us/windows/iot/iot-enterprise/deployment/install-winget-windows-iot
Hope it helps

**Comment by x157** [comment]
For anybody who **still** can't get this working...

I have a **brand new** Win 11 PC just unboxed today.  Winget refused to update, I was having the same errors listed above.

The official [Microsoft Install Powershell](https://learn.microsoft.com/en-us/windows/package-manager/winget/#install-winget) page says at the top "[get App Installer from the Microsoft Store](https://www.microsoft.com/p/app-installer/9nblggh4nns1#activetab=pivot:overviewtab)" **(If it's already installed, make sure it is updated with the latest version.)**

I did indeed have a version already installed, so I updated it.

After updating, I am able to `winget source update` from a non-elevated Powershell, and I can now see (and install!) a modern Powershell 7 via `winget`.

<img width="675" alt="Screenshot 2024-01-24 162048" src="https://github.com/microsoft/winget-cli/assets/25804900/8e836ae0-7f2d-465a-9665-04b2b507e7d4">

**Comment by martin-braun** [comment]
A fresh Windows 11 install is STILL affected. Why is this issue not pinned? Also, fix your product already. How can you screw up in such a way that the user has to repair the stock Windows to actually use it? Rhetorical question, nothing new with Microsoft.

**Comment by dustojnikhummer** [comment]
> A fresh Windows 11 install is STILL affected. Why is this issue not pinned? Also, fix your product already. How can you screw up in such a way that the user has to repair the stock Windows to actually use it? Rhetorical question, nothing new with Microsoft.

When I asked for a PS script to update Winget, I got told "Use the Windows Store". Yes, thanks for making Winget useless on a clean install Microsoft, now I need to keep software binaries in my install scripts. Basically I just got told "you are using it wrong"

**Comment by martin-braun** [comment]
@dustojnikhummer There are good reasons why I avoid Windows as much as possible and suggest against using it these days. Still have to deal with this telemetry bloat hog Windows shtt show. From stupid decisions in .NET to Candy Crash in the Start Menu. This OS is cancerous and I only install it as VM to compile software for it to serve users who also don't know what they are doing to themselves.

**Comment by dustojnikhummer** [comment]
> @dustojnikhummer There are good reasons why I avoid Windows as much as possible and suggest against using it these days. Still have to deal with this telemetry bloat hog Windows shtt show. From stupid decisions in .NET (like not preinstalling .NET Core) to Candy Crush in the Start Menu. This OS is cancerous, unreasonable and degenerated (you can't even put the taskbar on top anymore) and I only install it as VM to compile software for it to serve users who don't know what they are doing to themselves.
> 
> Whenever possible I pick mingw as part of my compiler toolchain to avoid having to use Windows for more than testing.

Yes, very helpful in corporate environment, thank you...

**Comment by jasonswearingen** [comment]
I had this problem yesterday (winget not working due to wrong CDN), here is my description and solution: https://github.com/ChrisTitusTech/winutil/issues/1082#issuecomment-1955819034

**Comment by dminhhoang26** [comment]
very tired, winget, windows. searching for many posts still getting stuck

**Comment by estomagado** [comment]
### TO ALL WHO WOULD FIND THIS IN THE FUTURE 

I was able to update the winget source using the correct filename and the following PoweShell command:

`Add-AppxPackage https://cdn.winget.microsoft.com/cache/source2.msix`

The "secret" is the new filename of the source file, that is not documented anywhere (at least, nowhere that the users can easily find).

The above command worked for me. If it does not work for you, there are other options suggested in this very issue [#3652] **that I did no test**, but may work. Do just ONE of them, not both!

- You can manually download the file from https://cdn.winget.microsoft.com/cache/source2.msix and use `Add-AppxPackage` locally
- `winget install -s msstore --id 9NBLGGH4NNS1`

Visit this for more info:
https://github.com/microsoft/winget-cli/issues/5368

**Comment by sharifhsn** [comment]
This solution works perfectly! To aid SEO:

This fixes the problem where winget cannot update source, and shows the following message:

Failed in attempting to update the source: winget

**Comment by UriF** [comment]
Today I experience the the same problem.  I tried sfc & DISM but no result.  

https://cdn.winget.microsoft.com/cache/source2.msix  - for old versions of winget.  for a new version you can download 
Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle

I tried it.  and it asked me if I want to re-install.  After approx 17% installation cancelled

**Comment by SalahAdDin** [comment]
> Add-AppxPackage https://cdn.winget.microsoft.com/cache/source2.msix

I ran this command many times, it didn't work!

**Comment by UriF** [comment]
Yesterday I found this command for Win 10. It resolved a problem

Please run Powershell as Administrator

Add-AppxPackage -DisableDevelopmentMode -Register (
[System.IO.Path]::Combine((Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller').'InstallLocation','appxmanifest.xml')
)

**Comment by x157** [comment]
> Any solution for Windows 11?

Windows 11 fix is here:
https://github.com/microsoft/winget-cli/issues/3652#issuecomment-1909141458

**Comment by UriF** [comment]
> > Yesterday I found this command for Win 10. It resolved a problem
> > Please run Powershell as Administrator
> > Add-AppxPackage -DisableDevelopmentMode -Register ( [System.IO.Path]::Combine((Get-AppxPackage -Name 'Microsoft.DesktopAppInstaller').'InstallLocation','appxmanifest.xml') )
> 
> Where did you find it? Any solution for Windows 11?

https://answers.microsoft.com/en-us/windows/forum/all/winget-upgrade-all-stop-working/27cbe9b1-e46e-4f3d-b56e-df464ef232b7

**Comment by nwtecx** [comment]
Here it was resolved by renaming the file '**winget**' to '**winget.old**';
Available at: **AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppInstaller**

**Comment by biergaizi** [comment]
Cross-posting from https://github.com/microsoft/winget-cli/issues/2879#issuecomment-3683187833 to here for visibility: Two years later, it's still a problem today in a fresh Windows 11 25H2 install with WinGet v1.9.25200. The original CDN problem is no longer relevant, but WinGet uses TLS certificate pinning, which must be constantly updated (see https://github.com/microsoft/winget-cli/pull/5140 https://github.com/microsoft/winget-cli/pull/5512 https://github.com/microsoft/winget-cli/pull/5732 https://github.com/microsoft/winget-cli/pull/5735). It has no mechanism to bootstrap a new one from itself, so you must wait for Windows to auto-update it - which doesn't happen immediately on a fresh system on first boot, only later at an random time.

Note that `https://aka.ms/getwinget` redirects to GitHub's `https://github.com/microsoft/winget-cli/releases/download/`. So make sure you have connectivity to GitHub, or use `https://cdn.winget.microsoft.com/cache/source2.msix` as suggested above.

```powershell
# doesn't work
> winget --version                                                               
v1.9.25200

# switch to the Downloads directory of the user directory
> cd ~/Downloads

# download latest WinGet
# Alternatively, use Invoke-WebRequest -Url https://aka.ms/getwinget -OutFile winget.msixbundle
# But Start-BitsTransfer has better performance, and with a progress bar
> Start-BitsTransfer -Source https://aka.ms/getwinget -Destination winget.msixbundle

# install
> Add-AppPackage ./winget.msixbundle

# works now
> winget --version
v1.12.350
```
