### ISSUE TITLE
winget.exe doesn't get installed after signing up to App Installer Insiders program

### ISSUE THREAD

**Issue by Caltor** [microsoft/winget-cli#391]
If App Installer is already installed before signing up to the App Installer Insider programme then winget.exe does not get installed into the AppData\Local\Microsoft\WindowsApp folder. There is no way to coax the Microsoft Store into updating the App Installer product as it is already installed and it cannot be uninstalled. Unfortunately this is likely hampering uptake of the winget package manager.

Several of us are experiencing this issue. For example @Pentao in https://github.com/microsoft/winget-cli/issues/210#issuecomment-632029939_ and at least 4 others in that thread. I have created this separate issue as that thread is about the issue when the winget.exe file is present but not in the PATH environment variable.

The workaround is to manually download and install the AppxBundle file from the releases of this project however the benefit of automatic upgrades is then lost.

**Comment by SayakMukhopadhyay** [comment]
So, I applied for the preview program around 12 hours ago when I wasnt getting the update and so I made the comment https://github.com/microsoft/winget-cli/issues/210#issuecomment-638357397 in #210 .

This morning I woke up to getting the update to App Installer and on updating I now have winget.

So, it seems like its just a matter of time before one gets access to the update.

**Comment by Caltor** [comment]
> This morning I woke up to getting the update to App Installer and on updating I now have winget.
> So, it seems like its just a matter of time before one gets access to the update.

@SayakMukhopadhyay Looking at my machine this morning (which I left on overnight) it seems to have updated with winget.exe as well. So the resolution to this issue appears to be "go to bed" :D or in other words be more patient! 

Admittedly I did install the appxbundle from the GitHib release tab before I went to bed but I can't see a way to uninstall that now; and it doesn't seem to be that copy of winget.exe as it is in a separate folder.

**Comment by Caltor** [comment]
Reopened due to https://github.com/microsoft/winget-cli/issues/210#issuecomment-640777179

**Comment by Caltor** [comment]
For anybody else affected by this issue, on my machine (which is now working) Get-AppxPackage Microsoft.DesktopAppInstaller gives version 1.0.41331.0 and if I look in AppData\Local\Microsoft\WindowsApps contains a winget.exe file.

**Comment by denelon** [comment]
For the sake of transparency here, we have a manual process to add accounts to the Package Manager insider program. There is also latency associated with getting the update from the store, and I don't yet know what the typical SLA is for the store to push the update. Many users have had to go to the store and "check for updates" to trigger the mechanism. As a reasonable expectation, I'd say one business day to get added to the insider ring. Once that's done it's a few minutes for the store to enable that user to get the update. I don't know the last SLA to have the store promote the update without interactive requests.

**Comment by doctordns** [comment]
Thanks!

**Comment by Caltor** [comment]
@denelon Appreciate your honesty! I have to say I'm really liking Microsoft under Satya Nadella.

**Comment by monreal** [comment]
FWIW I got a mail about being accepted into the Insiders program yesterday. Installed a fresh copy of the latest Windows 10 today, added my Microsoft account, clicked on the link mentioned in the mail. Store opened, App installer was updated. Still no "winget" for me. I then learned that App installer updated itself to 1.0.32912.0 which does not include "winget" yet.

I understand the problems regarding the manual process (thanks for the transparency!) but if there is a chance that thinks don't work when users receive the mail you should say so in the mail, it would have spared me about an hour of find-the-problem today.

**Comment by denelon** [comment]
I just pushed a new version out late yesterday. It's in Pre-Release here and should be in the Store for insiders.

Windows Package Manager v0.1.41821 Preview

If you still aren't able to get the correct version of the App Installer, please send an e-mail to winget-feedback@microsoft.com.

I'll check to make sure your MSA is configured correctly to be flighted for the Package Manager insider program. If you are running on a Windows Insider build, that should just work by default (assuming you're logged into the Store on that host with your insider MSA).

**Comment by zkascak** [comment]
I am having this issue as well. I have checked the environment variable and it is correct. I received the email and installed the linked version of App Installer from the Microsoft Store. I still am unable to access winget. 

I am currently running:

```powershell
PS C:\Users\zkasc> systeminfo /fo csv | ConvertFrom-Csv | select OS*, System*, Hotfix* | Format-List


OS Name             : Microsoft Windows 10 Home
OS Version          : 10.0.19041 N/A Build 19041
OS Manufacturer     : Microsoft Corporation
OS Configuration    : Standalone Workstation
OS Build Type       : Multiprocessor Free
System Boot Time    : 7/21/2020, 12:18:34 PM
System Manufacturer : LENOVO
System Model        : 81JB
System Type         : x64-based PC
System Directory    : C:\Windows\system32
System Locale       : en-us;English (United States)
Hotfix(s)           : 6 Hotfix(s) Installed.,[01]: KB4565627,[02]: KB4537759,[03]: KB4557968,[04]: KB4561600,[05]:
                      KB4566785,[06]: KB4565503
```

with the following version of App Installer


```powershell
PS C:\Users\zkasc> Get-AppxPackage Microsoft.DesktopAppInstaller


Name              : Microsoft.DesktopAppInstaller
Publisher         : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture      : X64
ResourceId        :
Version           : 1.0.32912.0
PackageFullName   : Microsoft.DesktopAppInstaller_1.0.32912.0_x64__8wekyb3d8bbwe
InstallLocation   : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.32912.0_x64__8wekyb3d8bbwe
IsFramework       : False
PackageFamilyName : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
PublisherId       : 8wekyb3d8bbwe
IsResourcePackage : False
IsBundle          : False
IsDevelopmentMode : False
NonRemovable      : False
Dependencies      : {Microsoft.VCLibs.140.00.UWPDesktop_14.0.27810.0_x64__8wekyb3d8bbwe,
                    Microsoft.VCLibs.140.00_14.0.27810.0_x64__8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.0.32912.0_neutral_split.scale-100_8wekyb3d8bbwe,
                    Microsoft.DesktopAppInstaller_1.0.32912.0_neutral_split.scale-150_8wekyb3d8bbwe}
IsPartiallyStaged : False
SignatureKind     : Store
Status            : Ok
```

**Comment by MisinformedDNA** [comment]
I signed up over two months ago and I still don't have access to the beta. I sent an email to winget-feedback@microsoft.com on Wednesday and have not heard back yet.

**Comment by denelon** [comment]
@MisinformedDNA has this issue been resolved for you?

**Comment by MisinformedDNA** [comment]
@denelon Nope. :(

> > Get-AppxPackage Microsoft.DesktopAppInstaller
> 
> RunspaceId             : 4d4a0e72-127d-41b2-9591-412fb8122d57
> Name                   : Microsoft.DesktopAppInstaller
> Publisher              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
> PublisherId            : 8wekyb3d8bbwe
> Architecture           : X64
> ResourceId             :
> Version                : 1.0.32912.0
> PackageFamilyName      : Microsoft.DesktopAppInstaller_8wekyb3d8bbwe
> PackageFullName        : Microsoft.DesktopAppInstaller_1.0.32912.0_x64__8wekyb3d8bbwe
> InstallLocation        : C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.0.32912.0_x64__8wekyb3d8bbwe
>

**Comment by MisinformedDNA** [comment]
@denelon Still nope.

**Comment by MisinformedDNA** [comment]
@denelon Upgraded Windows to v1909. Still nope.

**Comment by wintermute000** [comment]
Ditto, signed up and received the mail several days ago but still no winget being installled (no exe visible in folder, but path is OK). Tried on multiple machines including a fresh 20H2 build, no dice. very frustrating as I don't want to sideload / manually install, that kinda defeats the whole purpose of package management :/

**Comment by alvint** [comment]
Same as @MisinformedDNA here. I signed up and got the email, and I'm logged in to the Microsoft Store with that same email address, but it never offers a version of App Installer with winget. The version of App Installer it's giving me is 1.4.3161.0.

**Comment by wintermute000** [comment]
After 5 days its started working (had to update from Store), not sure if it was a lag or manually fixed by someone in the backend.

**Comment by alvint** [comment]
@wintermute000 What version did it finally give you?

**Comment by wintermute000** [comment]
C:\Users\xxx>winget --help
Windows Package Manager v0.2.3162 Preview

**Comment by fletchowns** [comment]
Took about a week for mine to finally update. Signed up for the package manager insiders program on Dec 24th and Microsoft Store updated App Installer to 1.11.3162.0 on Dec 31st. I tried a few times to manually check for updates on the app store between those dates but it didn't find any on my attempts.
```
PS C:\Users\fletch> winget --version
v0.2.3162 Preview
```

**Comment by wintermute000** [comment]
I think all this confusion would not occur if they didn't send you the signup complete email until AFTER you're 'truly' updated. Instead you get the email immediately, you think  you're signed up, and post the issue on github lol.

**Comment by PushOrigin** [comment]
I signed up a co-worker (I'm building up his computer before he starts here) on Monday 1/18. Two days later and he still doesn't have winget. I'm with you I'd rather install as "recommended:" from the store. Don't bother sending the email until it's ready. Or just stuff the damn thing into the regular App Installer, no one is going to use it unless they're looking for it and would have signed up as an insider anyway.

**Comment by MisinformedDNA** [comment]
It's been seven months since I've been waiting. No one's been able to help me. Looking at the commit history, I have to wonder if this is actually a priority for MS.

**Comment by denelon** [comment]
A few clarifying comments.

If you are running a Windows Insider build, the App Installer includes the Windows Package Manager.

If you are not running a Windows Insider Build, and you are not yet a Windows Package Manager insider, and you have the App Installer installed you will be able to get the update from the store (for the App Installer) once you are in the Windows Package Manager insider flight ring.

Our current process is only partially automated. We still have to manually add e-mail addresses to the flight ring after the Windows Package Manager insider form is completed. This is done daily in most cases. We do miss a day or two here or there. We're looking at automating the process. We don't control when the e-mail is going out, and it looks like that's happening upon form submission. We are looking into seeing what we can do to improve the experience.

**Comment by alvint** [comment]
@denelon How does one verify their address is in the flight ring? It has been over a month since I received the email and I still don't have the Insider version of App Installer.

**Comment by denelon** [comment]
All, we've been working on flighting processes and automation. The good news is you can download and install the signed package from the releases page, and once the insider ring is properly configured you should get the next update from the store automatically. We still have a manual step to add e-mail addresses to the ring. I still haven't gotten an automated solution working. If you are in the ring, and we publish a new update that doesn't automatically go to you, send an e-mail to winget-feedback@microsoft.com.

**Comment by masteroleg** [comment]
> All, we've been working on flighting processes and automation.

**Comment by denelon** [comment]
@masteroleg take a look at #210 there are several different possibilities. App Execution Alias, and the Path environment variable seem to be the two most common issues.

**Comment by masteroleg** [comment]
> @masteroleg take a look at #210 there are several different possibilities. App Execution Alias, and the Path environment variable seem to be the two most common issues.

I looked on #210 but can't fine exact advice what to do. All peoples ask question the same as me. #210 talk about version before v1.x .
I try to install  v1.12.11692.0, but unsuccessfully. How to install winget manually?

**Comment by denelon** [comment]
@masterdog, the most common path is to make sure you have a "current" working version of the App Installer. You should be able to download that from the store. Once you have a working version of the App Installer, you should be able to download and install the latest release from the GitHub [releases](https://github.com/microsoft/winget-cli/releases) page.

**Comment by masteroleg** [comment]
exactly v1.0.11692
<https://github.com/microsoft/winget-cli/releases/tag/v1.0.11692> does not
installing correctly, unfortunately
