### ISSUE TITLE
Winget error 0x80070490

### ISSUE THREAD

**Issue by dyllbert** [microsoft/winget-cli#5229]
### Brief description of your issue

Winget upgrade/install/list/etc... causes the following error:

Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070490 : Element not found.

### Steps to reproduce

Open powershell and run
`winget list`
or
`winget upgrade`
or
`winget install --id Microsoft.PowerShell --source winget`
etc...

### Expected behavior

- `winget list` should display installed packages
- `winget upgrade` should list available updates for installed packages
- `winget install --id Microsoft.PowerShell --source winget` should instal Powershell 7

### Actual behavior

All command get the following error:

Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070490 : Element not found.

### Environment

```shell
winget --info
Windows Package Manager v1.9.25200
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.26100.3194
System Architecture: X64
Package: Microsoft.DesktopAppInstaller v1.24.25200.0

Winget Directories
-----------------------------------------------------------------------------------------------------------------------
Logs                               %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\Diag…
User Settings                      %LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\sett…
Portable Links Directory (User)    %LOCALAPPDATA%\Microsoft\WinGet\Links
Portable Links Directory (Machine) C:\Program Files\WinGet\Links
Portable Package Root (User)       %LOCALAPPDATA%\Microsoft\WinGet\Packages
Portable Package Root              C:\Program Files\WinGet\Packages
Portable Package Root (x86)        C:\Program Files (x86)\WinGet\Packages
Installer Downloads                %USERPROFILE%\Downloads

Links
---------------------------------------------------------------------------
Privacy Statement   https://aka.ms/winget-privacy
License Agreement   https://aka.ms/winget-license
Third Party Notices https://aka.ms/winget-3rdPartyNotice
Homepage            https://aka.ms/winget
Windows Store Terms https://www.microsoft.com/en-us/storedocs/terms-of-sale

Admin Setting                             State
--------------------------------------------------
LocalManifestFiles                        Disabled
BypassCertificatePinningForMicrosoftStore Disabled
InstallerHashOverride                     Disabled
LocalArchiveMalwareScanOverride           Disabled
ProxyCommandLineOptions                   Disabled
DefaultProxy                              Disabled


I might just not know how to read the `winget --info` output, but it looks like it is reporting me being on Windows 10? here is the info from System -> About:
Edition	Windows 11 Home
Version	24H2
Installed on	‎9/‎18/‎2024
OS build	26100.3194
Experience	Windows Feature Experience Pack 1000.26100.48.0
```

**Comment by stephengillie** [comment]
Can you try `winget source reset`?

**Comment by dyllbert** [comment]
Commands and outputs below.  I had tried this before, I should have included it in my steps.

`winget source reset`
The following sources will be reset if the --force option is given:
Name    Argument                                      Explicit
\------------------------------------------------------
msstore https://storeedgefd.dsx.mp.microsoft.com/v9.0 false
winget  https://cdn.winget.microsoft.com/cache        false

`winget list`
Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070490 : Element not found.

`winget source reset --force`
Resetting all sources...Done

`winget list`
The 'msstore' source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires the current machine's 2-letter geographic region to be sent to the backend service to function properly (ex. "US").

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: Y [I entered 'Y' here]
Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070490 : Element not found.


It looks like it does reset, but ultimately still encounters the same problem. I should note, that I think it can "see" the sources just fine.  For example when the following command gets the following output:

`winget search Microsoft.Powershell`
Name                       Id                                            Version   Source
\------------------------------------------------------------------------
PowerShell               Microsoft.PowerShell              7.5.0.0   winget
PowerShell Preview Microsoft.PowerShell.Preview 7.6.0.2   winget

But then as mentioned attempting to install powershell (in this example) fails with the error posted.

**Comment by denelon** [comment]
This may have been corrected in the latest build. We're planning on releasing the upgrade next week. You could try the latest build, or you could try uninstalling the default "winget" source and then running a winget command to try to reinstall the default source.

**Comment by dyllbert** [comment]
It looks like my version is quite a few versions behind, `winget -v` gives me 1.9.25200  Any advice on how to manually update? I've tried the following:

- Download the latest (version 1.10.300) [Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle](https://github.com/microsoft/winget-cli/releases/download/v1.10.300/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.msixbundle) from the release pages and then click on the msixbundle.  It gives an error like this:
![Image](https://github.com/user-attachments/assets/da99eab2-549c-43fc-b5b4-3548b962f377)
- Use said version but install on powershell with `Add-AppxPackage -Path "path to msixbundle"`.  This results in a quick in line loading bar saying something like "Deployment progress" but it disappears almost immediately.
- I've checked the ms store (https://apps.microsoft.com/detail/9NBLGGH4NNS1?hl=en-us&gl=US&ocid=pdpshare) but it simply says I have it installed and has no option to manually update or uninstall for a reinstall.
- With winget. I think it goes without saying that if I can't install other things with winget, I can't update itself either.  But I did try it and get the same "0x80070490 : Element not found" error.

I would have thought winget gets updated with Windows updates, since its a built in part of Windows 11. Is there any other way to attempt to force an update?

**Comment by dyllbert** [comment]
I have updated to version 1.10.340 and still get the same error :/

**Comment by claus66** [comment]
We are having the same issue on 300+ Windows 11 23H2 devices (out of 20000 devices)

**Comment by denelon** [comment]
If you install the Microsoft.WinGet.Client PowerShell module and run `Repair-WinGetPackageManager -Latest -Force` does that resolve the issue?

**Comment by dyllbert** [comment]
Doesn't seem to do anything for me at least. I'll probably try a full windows wipe and reinstall, but haven't had time.

**Comment by denelon** [comment]
@dylbert would you be willing to run `winget list --verbose-logs --logs` and share the logfile? That might give a hint as to what's happening.

**Comment by dyllbert** [comment]
Sure here is the terminal output
`winget list --verbose-logs --logs`
```
Failed to open the predefined source; please report to winget maintainers.
An unexpected error occurred while executing the command:
0x80070490 : Element not found.
```

And then it generates this log file:

[WinGet-2025-03-18-17-06-10.180.log](https://github.com/user-attachments/files/19329657/WinGet-2025-03-18-17-06-10.180.log)
