### ISSUE TITLE
Unable to install *anything* - "The parameter is incorrect."

### ISSUE THREAD

**Issue by stvhwrd** [microsoft/winget-cli#573]
# Brief description of your issue

Every time I try to install a package, any package at all, I get an error dialog with "The parameter is incorrect." I have previously installed ~dozen packages without incident.

![image](https://user-images.githubusercontent.com/4117011/93398816-1bb2a580-f831-11ea-95d6-c840cad0cef1.png)

# Steps to reproduce

In PowerShell window (Admin or normal, makes no difference) install any valid package:
`winget install Microsoft.VisualStudioCode`

(using VSCode as arbitrary example)

# Expected behavior

I expect the package to be installed successfully.

# Actual behavior

The PowerShell window hangs and an error dialog pops up with the error "The parameter is incorrect", with title bar of this dialog showing the installer of the package I'm trying to install.  After clicking "OK" in dialog, it disappears and the PS windows shows "Installer failed with exit code: 1223"

![image](https://user-images.githubusercontent.com/4117011/93399145-c9be4f80-f831-11ea-8b6e-c90efcfad885.png)

# Environment

```none
Windows Package Manager v0.2.2521 Preview
Windows: Windows.Desktop v10.0.19041.508
Package: Microsoft.DesktopAppInstaller v1.11.2521.0

Tried this in PowerShell v7.0.3, Windows Terminal Version: 1.2.2381.0
```

**Comment by denelon** [comment]
Would you be willing to share your logs for the package manager?

**Comment by stvhwrd** [comment]
Sure, no problem!  What's the process?

**Comment by denelon** [comment]
%LOCALAPPDATA%\Packages\Microsoft.DesktopAppInstaller_8wekyb3d8bbwe\LocalState\DiagOutputDir

The path above should get you to the log files so we can see what's being reported.

**Comment by stvhwrd** [comment]
And I should send to secure@microsoft.com with a reference to this issue?

**Comment by denelon** [comment]
No, you can e-mail the logs to winget-feedback@microsoft.com

**Comment by denelon** [comment]
The "secure@microsoft.com" alias is for more sensitive log issues related to security concerns. These logs don't contain any sensitive information in them.

**Comment by stvhwrd** [comment]
Got it, thanks.  Sent the logs.

**Comment by denelon** [comment]
We have received them, and will take a look. Thank you very much for sharing!

**Comment by KevinLaMS** [comment]
@stvhwrd  out of curiosity, if you remove powershell from the equation do you still see the error?  in other words from a command prompt if you just type "winget install microsoft.visualstudiocode" do you get the same error?  Thanks

**Comment by stvhwrd** [comment]
Using vanilla cmd.exe, it's the exact same result.

**Comment by KevinLaMS** [comment]
Thanks for the quick response.

**Comment by JohnMcPMS** [comment]
Is this behavior new since the OS update?  Or have you successfully installed since getting `Windows.Desktop v10.0.19041.508`, which appears to have been released Sept. 8?

**Comment by stvhwrd** [comment]
I hadn't taken note of exact date this first started occurring but no, it's been at least a month... realistically it's probably closer to 3 months.

**Comment by JohnMcPMS** [comment]
Sorry, it has been happening for 3 months or it has been 3 months since you last tried?

**Comment by stvhwrd** [comment]
This first started happening approximately 2-3 months ago.

**Comment by JohnMcPMS** [comment]
I have a suspicion; do you have any shell verbs registered for exes?  If you right click on an exe, which action is in bold?

**Comment by stvhwrd** [comment]
Negative.

![image](https://user-images.githubusercontent.com/4117011/93542243-5984fc00-f90d-11ea-8337-562c76ff9e6a.png)

**Comment by JohnMcPMS** [comment]
It could potentially still be this, but I suspect it less now.  We aren't setting the verb on the ShellExecute call, and so the default action should occur.  We should set it to `open` in case someone changes the default verb to something else.

At this point, I'm not sure how else to investigate.  ShellExecute is a complex API that does a LOT even just to launch an executable.  We are using it because it handles many security checks for us, but it definitely is a bit opaque.

The only thing I can think of at this point is attaching a debugger to see if the error comes out in debug output.  If you are ok with helping that way, I can detail how to do that.

**Comment by stvhwrd** [comment]
Yeah for sure, happy to help however I can!  I love this project/intention.

Feel free to ping me on Teams - alias is `stehowa`

**Comment by luispb** [comment]
I'm experiencing the same issue. This is the error for example when I try to install Audacity.
![image](https://user-images.githubusercontent.com/2574334/93719184-28146680-fb81-11ea-8eab-07da3134c032.png)

![image](https://user-images.githubusercontent.com/2574334/93719194-395d7300-fb81-11ea-8f2d-fabb820ce75a.png)

**Comment by denelon** [comment]
As an FYI, if you use Windows Feedback [Windows]+[f] and select "Apps" and "Windows Package Manager" for the category it will automatically attach logs.

**Comment by luispb** [comment]
> As an FYI, if you use Windows Feedback [Windows]+[f] and select "Apps" and "Windows Package Manager" for the category it will automatically attach logs.

Good to know!

**Comment by denelon** [comment]
@stvhwrd has this issue been resolved?

**Comment by stvhwrd** [comment]
Not resolved, @JohnMcPMS has done some debugging on my machine on corpnet.  Issue persists.

**Comment by denelon** [comment]
Thanks for letting us know. I've removed the "Needs-Attention".

**Comment by dantho** [comment]
BTW, I'm getting this same, bizarre error message in PowerShell 7.1.0 Core (installed today) when I run a trivial .bat script from _certain_ directories.  (Older version of PowerShell desktop works fine on the same .bat script.)

PS C: > echo 'echo "Hello"' > hello.bat
PS C: > .\hello.bat
Hello
-----------------------------------------
PS M: > echo 'echo "Hello"' > hello.bat
PS M: > .\hello.bat
OperationStopped: The parameter is incorrect.

The M-Drive is a networked drive automagically mounted by our rev control software, so it is "special", but not dramatically so.
I've worked this way forever.  And the older version of PowerShell desktop works.  I think I'll go back to Core 7.0.3 and see if it works.

**Comment by JohnMcPMS** [comment]
I've figured out the issue, and fortunately it is already resolved in the next client release.

I was able to repro on a machine thanks to @stvhwrd , and found that the problem comes from placing the [MotW](https://textslashplain.com/2016/04/04/downloads-and-the-mark-of-the-web/) on the downloaded file.  When it is Zone 3, affected machines will generate the invalid parameter error from within the kernel process creation, while also strangely removing the Zone.Identifier alternate stream.  I can only assume that this is some particular AV driver or specific enterprise security enforcement, because it does not affect many people.

When I manually set the Zone.Identifier to Zone 2, like we are now doing for trusted sources, the process creation does not fail, and the Zone.Identifier alternate stream is not removed.

I believe that we are very close to releasing the next version that includes the Zone change, and will work with @denelon to get it to you as soon as we can.

**Comment by denelon** [comment]
This issue should be resolved.

**Comment by stvhwrd** [comment]
@denelon resolved how, by what, and when?  Still an issue for me.

```
winget --info
Windows Package Manager v0.2.2941 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.685
Package: Microsoft.DesktopAppInstaller v1.11.2941.0
```

**Comment by JohnMcPMS** [comment]
It should be fixed in https://github.com/microsoft/winget-cli/releases/tag/v0.2.3162-preview , @denelon , was this pushed out to the Store flight?

**Comment by ellielo** [comment]
Did you fix it?
