### ISSUE TITLE
Errors occur when using network functions 

### ISSUE THREAD

**Issue by CausingBrick** [microsoft/winget-cli#731]
# Brief description of your issue

When using network functions, such as `install`, `search` and `show`, winget always loading a long time then showing up errors like bellow.
```
PS C:\Users\causingbrick> winget  search powertoys
Failed to open the source; try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
InternetReadFile() failed.
0x80072ee2 : unknown error
```
Following the prompts, I have tried to execute the `winget source reset command`  with administrator privileges in PowerShell and turn off the windows firewall  but it still doesn't work.

# Steps to reproduce

Using winget network functions such as `install`, `search` and `show`.

# Expected behavior

It can perform functions normally.

# Actual behavior

Showing up errors
```
Failed to open the source; try the 'source reset' command if the problem persists.
An unexpected error occurred while executing the command:
InternetReadFile() failed.
0x80072ee2 : unknown error
```
# Environment

```none
[winget --info]
Windows Package Manager v0.2.3162 Preview
Copyright (c) Microsoft Corporation. All rights reserved.

Windows: Windows.Desktop v10.0.19042.746
Package: Microsoft.DesktopAppInstaller v1.11.3162.0

```

```
[ping winget source]
[ipv4]
➜  causingbrick ping winget.azureedge.net
PING cs9.wpc.v0cdn.net (117.18.232.200) 56(84) bytes of data.
64 bytes from 117.18.232.200 (117.18.232.200): icmp_seq=1 ttl=50 time=201 ms
64 bytes from 117.18.232.200 (117.18.232.200): icmp_seq=2 ttl=50 time=206 ms
64 bytes from 117.18.232.200 (117.18.232.200): icmp_seq=3 ttl=50 time=195 ms
^C
--- cs9.wpc.v0cdn.net ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2218ms
rtt min/avg/max/mdev = 194.787/200.834/206.498/4.788 ms

[ipv6]
PS C:\Users\causingbrick> ping winget.azureedge.net

Pinging cs9.wpc.v0cdn.net [2606:2800:147:120f:30c:1ba0:fc6:265a] with 32 bytes of data:
Reply from 2606:2800:147:120f:30c:1ba0:fc6:265a: time=504ms
Reply from 2606:2800:147:120f:30c:1ba0:fc6:265a: time=504ms
Reply from 2606:2800:147:120f:30c:1ba0:fc6:265a: time=504ms

Ping statistics for 2606:2800:147:120f:30c:1ba0:fc6:265a:
    Packets: Sent = 3, Received = 3, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 504ms, Maximum = 504ms, Average = 504ms
```

**Comment by denelon** [comment]
We've released a newer version of the Windows Package Manager. Can you check the store and get the upgrade to the "App Installer"? There were some network optimizations recently implemented.

**Comment by CausingBrick** [comment]
> We've released a newer version of the Windows Package Manager. Can you check the store and get the upgrade to the "App Installer"? There were some network optimizations recently implemented.

Thank you for your help, but I checked that there is no upgrade for "App Installer" in the store, and the version information of `winget --info` is still the same as given above.

**Comment by jedieaston** [comment]
You can manually install it from this release: https://github.com/microsoft/winget-cli/releases/tag/v-0.2.10191-preview

**Comment by CausingBrick** [comment]
It works, although it takes a long time to load, but no error occurs. Thanks for your help!
